# A Swagger 3.0.0 (a.k.a. OpenAPI) definition of the Engine API.
#
# Some style notes:
# - This file is used by ReDoc, which allows GitHub Flavored Markdown in
#   descriptions.
# - There is no maximum line length, for ease of editing and pretty diffs.
# - operationIds are in the format of "verb" + "noun".

openapi: "3.0.0"

## Information
info:
  version: 2.0.8
  title: Canonn APIv2
  x-logo:
    url: "./canonn-logo.png"
  description: |
    An API for all the Science related information Canonn has in its datastores stored on the Gnosis, built using [Strapi](https://strapi.io) a Nodejs API framework.

    # Documentation
    We have two different documentation types

    * [Redocs](./)
    * [Swagger-UI](./swaggerui)

    You can view our Swagger/OpenAPI on [CAPIv2-Swagger Github](https://github.com/canonn-science/CAPIv2-Swagger) and our API development [CAPIv2-Strapi Github](https://github.com/canonn-science/CAPIv2-Strapi).

    We also automatically build our current Development branch before deploying to the Alpha server, you can see our [Travis-CI](https://travis-ci.org/canonn-science/CAPIv2-Strapi) build status.

    # Servers

    We also have 3 API servers; Live (Production), Beta (Staging), Alpha (Development). You should use the Beta server for testing your application prior to using the Live server. The Alpha server is used by Canonn to test our changes prior to releasing a new version.

    Data between the Live and Beta servers are replicated as needed, eventually we plan to dynamically replicate the data every night at midnight Phoenix, Arizona USA time (MST-Arizona GMT-7)

    Server Name  | Server Type | Server URL | Server version
    ---------|---------|---------|---------
    Live | Production | https://api.canonn.tech | v2.0.7
    Beta | Production | https://api.canonn.tech:2053 | v2.0.7
    Alpha | Production | https://api.canonn.tech:2083 | v2.0.8

    Thank you for your support, and thank you to all the CMDRs who supply us with our data!

  contact:
    name: Canonn R&D Team
    email: rd@canonn.technology
    url: https://canonn.science
  license:
    name: MIT
    url: https://github.com/canonn-science/CAPIv2-Strapi/blob/development/LICENSE

## Servers
servers:
  - url: https://api.canonn.tech:2053
    description: Beta Staging Server, should be used to test your application prior to deployment. Data is mirrored from Production every few hours.
  - url: https://api.canonn.tech
    description: Live Production Server, should be used if your application has been tested and deployed
  - url: https://api.canonn.tech:2083
    description: Alpha Development Server, used by Canonn to test development prior to updating Staging and Production. Data here is likely to be wrong or inaccurate.

## Paths
paths:

# Authentication
  /auth/local:
    post:
      tags:
        - Local Auth
      summary: Login to the Canonn APIv2 Server
      description: Using local authentication to login to the API, user must already be registered
      operationId: loginLocal
      security: []
# BM Report
  /bmreport/count:
    get:
      tags:
        - Bark Mound Reports
      summary: Get a count of all BM Reports
      description: The API will respond with just a number, which is the total amount of reports on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getBMReportsCount
      security: []
  /bmreport:
    get:
      tags:
        - Bark Mound Reports
      summary: Get a list of BM Reports
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getBMReports
      security: []
    post:
      tags:
        - Bark Mound Reports
      summary: Post a new BM Report
      description: To be used to submit new Reports to Canonn, note that the reportStatus should always be pending
      operationId: submitBMReport
      security: []
  /bmreport/{id}:
    get:
      tags:
        - Bark Mound Reports
      summary: Get a Single BM Report
      description: Provide the ID to get a single report
      operationId: getBMReportById
      security: []
    put:
      tags:
        - Bark Mound Reports
      summary: Update a BM Report
      description: You do not need to send the entire report again, you can send only changed fields
      operationId: updateBMReportById
      security: []
    delete:
      tags:
        - Bark Mound Reports
      summary: Delete a BM Report
      description: The response is just an empty JSON, deleting a report requires auth
      operationId: removeBMReportById
      security:
        - canonnAuth: [reportDelete]
# BM Site
  /bmsite/count:
    get:
      tags:
        - Bark Mounds
      summary: Get a count of all BM Sites
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getBMSitesCount
      security: []
  /bmsite:
    get:
      tags:
        - Bark Mounds
      summary: Get a list of BM Sites
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getBMSites
      security: []
    post:
      tags:
        - Bark Mounds
      summary: Post a new BM Site
      description: To be used to add a new site to the Canonn database, these are sites verified by Canonn
      operationId: submitBMSite
      security:
        - canonnAuth: [siteWrite]
  /bmsite/{id}:
    get:
      tags:
        - Bark Mounds
      summary: Get a Single BM Site
      description: Provide the ID to get a single site
      operationId: getBMSiteById
      security: []
    put:
      tags:
        - Bark Mounds
      summary: Update a BM Site
      description: You do not need to send the entire site again, you can send only changed fields
      operationId: updateBMSiteById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Bark Mounds
      summary: Delete a BM Site
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeBMSiteById
      security:
        - canonnAuth: [siteDelete]
# Body
  /body/count:
    get:
      tags:
        - Bodies
      summary: Get a count of all Bodies
      description: The API will respond with just a number, which is the total amount of bodies on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getBodiesCount
      security: []
  /body:
    get:
      tags:
        - Bodies
      summary: Get a list of Bodies
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getBodies
      security: []
    post:
      tags:
        - Bodies
      summary: Post a new Body
      description: To be used to add a new body to the Canonn database
      operationId: submitBody
      security:
        - canonnAuth: [locationWrite]
  /body/{id}:
    get:
      tags:
        - Bodies
      summary: Get a Single Body
      description: Provide the ID to get a single body
      operationId: getBodyById
      security: []
    put:
      tags:
        - Bodies
      summary: Update a Body
      description: You do not need to send the entire site again, you can send only changed fields
      operationId: updateBodyById
      security:
        - canonnAuth: [locationWrite]
    delete:
      tags:
        - Bodies
      summary: Delete a Body
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeBodyById
      security:
        - canonnAuth: [locationDelete]
# BT Report
  /btreport/count:
    get:
      tags:
        - Brain Tree Reports
      summary: Get a count of all BT Reports
      description: The API will respond with just a number, which is the total amount of reports on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getBTReportsCount
      security: []
  /btreport:
    get:
      tags:
        - Brain Tree Reports
      summary: Get a list of BT Reports
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getBTReports
      security: []
    post:
      tags:
        - Brain Tree Reports
      summary: Post a new BT Report
      description: To be used to submit new Reports to Canonn, note that the reportStatus should always be pending
      operationId: submitBTReport
      security: []
  /btreport/{id}:
    get:
      tags:
        - Brain Tree Reports
      summary: Get a Single BT Report
      description: Provide the ID to get a single report
      operationId: getBTReportById
      security: []
    put:
      tags:
        - Brain Tree Reports
      summary: Update a BT Report
      description: You do not need to send the entire report again, you can send only changed fields
      operationId: updateBTReportById
      security: []
    delete:
      tags:
        - Brain Tree Reports
      summary: Delete a BT Report
      description: The response is just an empty JSON, deleting a report requires auth
      operationId: removeBTReportById
      security:
        - canonnAuth: [reportDelete]
# BT Site
  /btsite/count:
    get:
      tags:
        - Brain Trees
      summary: Get a count of all BT Sites
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getBTSitesCount
      security: []
  /btsite:
    get:
      tags:
        - Brain Trees
      summary: Get a list of BT Sites
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getBTSites
      security: []
    post:
      tags:
        - Brain Trees
      summary: Post a new BT Site
      description: To be used to add a new site to the Canonn database, these are sites verified by Canonn
      operationId: submitBTSite
      security:
        - canonnAuth: [siteWrite]
  /btsite/{id}:
    get:
      tags:
        - Brain Trees
      summary: Get a Single BT Site
      description: Provide the ID to get a single site
      operationId: getBTSiteById
      security: []
    put:
      tags:
        - Brain Trees
      summary: Update a BT Site
      description: You do not need to send the entire site again, you can send only changed fields
      operationId: updateBTSiteById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Brain Trees
      summary: Delete a BT Site
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeBTSiteById
      security:
        - canonnAuth: [siteDelete]
# CMDR
  /cmdr/count:
    get:
      tags:
        - CMDRs
      summary: Get a count of all CMDRs
      description: The API will respond with just a number, which is the total amount of CMDRs on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getCMDRsCount
      security: []
  /cmdr:
    get:
      tags:
        - CMDRs
      summary: Get a list of CMDRs
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getCMDRs
      security: []
    post:
      tags:
        - CMDRs
      summary: Post a new CMDR
      description: To be used to add new CMDRs to our list, updated from reports submitted to us
      operationId: submitCMDR
      security:
        - userAuth: [cmdrWrite]
  /cmdr/{id}:
    get:
      tags:
        - CMDRs
      summary: Get a Single CMDR
      description: Provide the ID to get a single CMDR
      operationId: getCMDRById
      security: []
    put:
      tags:
        - CMDRs
      summary: Update a CMDR
      description: Used to update the CMDR name
      operationId: updateCMDRById
      security:
        - userAuth: [cmdrWrite]
    delete:
      tags:
        - CMDRs
      summary: Delete a CMDR
      description: The response is just an empty JSON, deleting a report requires auth
      operationId: removeCMDRById
      security:
        - canonnAuth: [cmdrDelete]
# Faction Kill Report
  /factionkillreport/count:
    get:
      tags:
        - CMDRs
      summary: Get a count of all Faction Kill Reports
      description: The API will respond with just a number, which is the total amount of reports on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getFactionKillReportsCount
      security: []
  /factionkillreport:
    get:
      tags:
        - CMDRs
      summary: Get a list of Faction Kill Reports
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getFGReports
      security: []
    post:
      tags:
        - CMDRs
      summary: Post a new Faction Kill Report
      description: To be used to submit new Reports to Canonn, note that the reportStatus should always be pending
      operationId: submitFGReport
      security: []
  /factionkillreport/{id}:
    get:
      tags:
        - CMDRs
      summary: Get a Single Faction Kill Report
      description: Provide the ID to get a single report
      operationId: getFGReportById
      security: []
    put:
      tags:
        - CMDRs
      summary: Update a Faction Kill Report
      description: You do not need to send the entire report again, you can send only changed fields
      operationId: updateFGReportById
      security: []
    delete:
      tags:
        - CMDRs
      summary: Delete a Faction Kill Report
      description: The response is just an empty JSON, deleting a report requires auth
      operationId: removeFGReportById
      security:
        - canonnAuth: [cmdrDelete]
# FG Report
  /fgreport/count:
    get:
      tags:
        - Fungal Gourd Reports
      summary: Get a count of all FG Reports
      description: The API will respond with just a number, which is the total amount of reports on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getFGReportsCount
      security: []
  /fgreport:
    get:
      tags:
        - Fungal Gourd Reports
      summary: Get a list of FG Reports
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getFGReports
      security: []
    post:
      tags:
        - Fungal Gourd Reports
      summary: Post a new FG Report
      description: To be used to submit new Reports to Canonn, note that the reportStatus should always be pending
      operationId: submitFGReport
      security: []
  /fgreport/{id}:
    get:
      tags:
        - Fungal Gourd Reports
      summary: Get a Single FG Report
      description: Provide the ID to get a single report
      operationId: getFGReportById
      security: []
    put:
      tags:
        - Fungal Gourd Reports
      summary: Update a FG Report
      description: You do not need to send the entire report again, you can send only changed fields
      operationId: updateFGReportById
      security: []
    delete:
      tags:
        - Fungal Gourd Reports
      summary: Delete a FG Report
      description: The response is just an empty JSON, deleting a report requires auth
      operationId: removeFGReportById
      security:
        - canonnAuth: [reportDelete]
# FG Site
  /fgsite/count:
    get:
      tags:
        - Fungal Gourds
      summary: Get a count of all FG Sites
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getFGSitesCount
      security: []
  /fgsite:
    get:
      tags:
        - Fungal Gourds
      summary: Get a list of FG Sites
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getFGSites
      security: []
    post:
      tags:
        - Fungal Gourds
      summary: Post a new FG Site
      description: To be used to add a new site to the Canonn database, these are sites verified by Canonn
      operationId: submitFGSite
      security:
        - canonnAuth: [siteWrite]
  /fgsite/{id}:
    get:
      tags:
        - Fungal Gourds
      summary: Get a Single FG Site
      description: Provide the ID to get a single site
      operationId: getFGSiteById
      security: []
    put:
      tags:
        - Fungal Gourds
      summary: Update a FG Site
      description: You do not need to send the entire site again, you can send only changed fields
      operationId: updateFGSiteById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Fungal Gourds
      summary: Delete a FG Site
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeFGSiteById
      security:
        - canonnAuth: [siteDelete]
# FM Report
  /fmreport/count:
    get:
      tags:
        - Fumarole Reports
      summary: Get a count of all FM Reports
      description: The API will respond with just a number, which is the total amount of reports on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getFMReportsCount
      security: []
  /fmreport:
    get:
      tags:
        - Fumarole Reports
      summary: Get a list of FM Reports
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getFMReports
      security: []
    post:
      tags:
        - Fumarole Reports
      summary: Post a new FM Report
      description: To be used to submit new Reports to Canonn, note that the reportStatus should always be pending
      operationId: submitFMReport
      security: []
  /fmreport/{id}:
    get:
      tags:
        - Fumarole Reports
      summary: Get a Single FM Report
      description: Provide the ID to get a single report
      operationId: getFMReportById
      security: []
    put:
      tags:
        - Fumarole Reports
      summary: Update a FM Report
      description: You do not need to send the entire report again, you can send only changed fields
      operationId: updateFMReportById
      security: []
    delete:
      tags:
        - Fumarole Reports
      summary: Delete a FM Report
      description: The response is just an empty JSON, deleting a report requires auth
      operationId: removeFMReportById
      security:
        - canonnAuth: [reportDelete]
# FM Site
  /fmsite/count:
    get:
      tags:
        - Fumaroles
      summary: Get a count of all FM Sites
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getFMSitesCount
      security: []
  /fmsite:
    get:
      tags:
        - Fumaroles
      summary: Get a list of FM Sites
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getFMSites
      security: []
    post:
      tags:
        - Fumaroles
      summary: Post a new FM Site
      description: To be used to add a new site to the Canonn database, these are sites verified by Canonn
      operationId: submitFMSite
      security:
        - canonnAuth: [siteWrite]
  /fmsite/{id}:
    get:
      tags:
        - Fumaroles
      summary: Get a Single FM Site
      description: Provide the ID to get a single site
      operationId: getFMSiteById
      security: []
    put:
      tags:
        - Fumaroles
      summary: Update a FM Site
      description: You do not need to send the entire site again, you can send only changed fields
      operationId: updateFMSiteById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Fumaroles
      summary: Delete a FM Site
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeFMSiteById
      security:
        - canonnAuth: [siteDelete]
# FM Type
  /fmsitetype/count:
    get:
      tags:
        - Fumaroles
      summary: Get a count of all FM Site Types
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getFMSiteTypesCount
      security: []
  /fmsitetype:
    get:
      tags:
        - Fumaroles
      summary: Get a list of FM Site Types
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getFMSiteTypes
      security: []
    post:
      tags:
        - Fumaroles
      summary: Post a new FM Site Type
      description: To be used to add a new site type to the Canonn database
      operationId: submitFMSiteType
      security:
        - canonnAuth: [siteWrite]
  /fmsitetype/{id}:
    get:
      tags:
        - Fumaroles
      summary: Get a Single FM Site Type
      description: Provide the ID to get a single site
      operationId: getFMSiteTypeById
      security: []
    put:
      tags:
        - Fumaroles
      summary: Update a FM Site Type
      description: The type should match those used by EDSM if appropriate
      operationId: updateFMSiteTypeById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Fumaroles
      summary: Delete a FM Site Type
      description: The response is just an empty JSON, deleting a site type requires auth
      operationId: removeFMSiteTypeById
      security:
        - canonnAuth: [siteDelete]
# GEN Report
  /genreport/count:
    get:
      tags:
        - Generation Ship Reports
      summary: Get a count of all GEN Reports
      description: The API will respond with just a number, which is the total amount of reports on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGENReportsCount
      security: []
  /genreport:
    get:
      tags:
        - Generation Ship Reports
      summary: Get a list of GEN Reports
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGENReports
      security: []
    post:
      tags:
        - Generation Ship Reports
      summary: Post a new GEN Report
      description: To be used to submit new Reports to Canonn, note that the reportStatus should always be pending
      operationId: submitGENReport
      security: []
  /genreport/{id}:
    get:
      tags:
        - Generation Ship Reports
      summary: Get a Single GEN Report
      description: Provide the ID to get a single report
      operationId: getGENReportById
      security: []
    put:
      tags:
        - Generation Ship Reports
      summary: Update a GEN Report
      description: You do not need to send the entire report again, you can send only changed fields
      operationId: updateGENReportById
      security: []
    delete:
      tags:
        - Generation Ship Reports
      summary: Delete a GEN Report
      description: The response is just an empty JSON, deleting a report requires auth
      operationId: removeGENReportById
      security:
        - canonnAuth: [reportDelete]
# GEN Site
  /gensite/count:
    get:
      tags:
        - Generation Ships
      summary: Get a count of all GEN Sites
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGENSitesCount
      security: []
  /gensite:
    get:
      tags:
        - Generation Ships
      summary: Get a list of GEN Sites
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGENSites
      security: []
    post:
      tags:
        - Generation Ships
      summary: Post a new GEN Site
      description: To be used to add a new site to the Canonn database, these are sites verified by Canonn
      operationId: submitGENSite
      security:
        - canonnAuth: [siteWrite]
  /gensite/{id}:
    get:
      tags:
        - Generation Ships
      summary: Get a Single GEN Site
      description: Provide the ID to get a single site
      operationId: getGENSiteById
      security: []
    put:
      tags:
        - Generation Ships
      summary: Update a GEN Site
      description: You do not need to send the entire site again, you can send only changed fields
      operationId: updateGENSiteById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Generation Ships
      summary: Delete a GEN Site
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeGENSiteById
      security:
        - canonnAuth: [siteDelete]
# GR Active Group
  /gractivegroup/count:
    get:
      tags:
        - Guardian Ruins
      summary: Get a count of all GR Active Groups
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGRSiteActiveGroupsCount
      security: []
  /gractivegroup:
    get:
      tags:
        - Guardian Ruins
      summary: Get a list of GR Site Active Groups
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGRSiteActiveGroups
      security: []
    post:
      tags:
        - Guardian Ruins
      summary: Post a new GR Site Active Group
      description: To be used to add a new site to the Canonn database, these are sites verified by Canonn
      operationId: submitGRSiteActiveGroup
      security:
        - canonnAuth: [siteWrite]
  /gractivegroup/{id}:
    get:
      tags:
        - Guardian Ruins
      summary: Get a Single GR Site Active Group
      description: Provide the ID to get a single site
      operationId: getGRSiteActiveGroupById
      security: []
    put:
      tags:
        - Guardian Ruins
      summary: Update a GR Site Active Group
      description: Used to change the active group, be sure there are no duplicates
      operationId: updateGRSiteActiveGroupById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Guardian Ruins
      summary: Delete a GR Site Active Group
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeGRSiteActiveGroupById
      security:
        - canonnAuth: [siteDelete]
# GR Active Obelisk
  /gractiveobelisk/count:
    get:
      tags:
        - Guardian Ruins
      summary: Get a count of all GR Active Obelisks
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGRSiteActiveObelisksCount
      security: []
  /gractiveobelisk:
    get:
      tags:
        - Guardian Ruins
      summary: Get a list of GR Site Active Obelisks
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGRSiteActiveObelisks
      security: []
    post:
      tags:
        - Guardian Ruins
      summary: Post a new GR Site Active Obelisk
      description: To be used to add a new site to the Canonn database, these are sites verified by Canonn
      operationId: submitGRSiteActiveObelisk
      security:
        - canonnAuth: [siteWrite]
  /gractiveobelisk/{id}:
    get:
      tags:
        - Guardian Ruins
      summary: Get a Single GR Site Active Obelisk
      description: Provide the ID to get a single site
      operationId: getGRSiteActiveObeliskById
      security: []
    put:
      tags:
        - Guardian Ruins
      summary: Update a GR Site Active Obelisk
      description: Used to change the active obelisk, be sure there are no duplicates
      operationId: updateGRSiteActiveObeliskById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Guardian Ruins
      summary: Delete a GR Site Active Obelisk
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeGRSiteActiveObeliskById
      security:
        - canonnAuth: [siteDelete]
# GR Artifact
  /grartifact/count:
    get:
      tags:
        - Guardian Ruins
      summary: Get a count of all GR Site Artifacts
      description: The API will respond with just a number, which is the total amount of artifacts on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGRArtifactsCount
      security: []
  /grartifact:
    get:
      tags:
        - Guardian Ruins
      summary: Get a list of GR Site Artifacts
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGRArtifacts
      security: []
    post:
      tags:
        - Guardian Ruins
      summary: Post a new GR Site Artifact
      description: To be used to add a new artifact to the Canonn database
      operationId: submitGRArtifact
      security:
        - canonnAuth: [siteWrite]
  /grartifact/{id}:
    get:
      tags:
        - Guardian Ruins
      summary: Get a Single GR Site Artifact
      description: Provide the ID to get a single artifact
      operationId: getGRArtifactById
      security: []
    put:
      tags:
        - Guardian Ruins
      summary: Update a GR Site Artifact
      description: Used to update the artifact
      operationId: updateGRArtifactById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Guardian Ruins
      summary: Delete a GR Site Artifact
      description: The response is just an empty JSON, deleting an artifact requires auth
      operationId: removeGRArtifactById
      security:
        - canonnAuth: [siteDelete]
# GR Codex Category
  /grcodexcategory/count:
    get:
      tags:
        - Guardian Ruins
      summary: Get a count of all GR Site Codex Categories
      description: The API will respond with just a number, which is the total amount of codex categories on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGRCodexCategoriesCount
      security: []
  /grcodexcategory:
    get:
      tags:
        - Guardian Ruins
      summary: Get a list of GR Site Codex Categories
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGRCodexCategories
      security: []
    post:
      tags:
        - Guardian Ruins
      summary: Post a new GR Site Codex Category
      description: To be used to add a new codex category to the Canonn database
      operationId: submitGRCodexCategory
      security:
        - canonnAuth: [siteWrite]
  /grcodexcategory/{id}:
    get:
      tags:
        - Guardian Ruins
      summary: Get a Single GR Site Codex Category
      description: Provide the ID to get a single codex category
      operationId: getGRCodexCategoryById
      security: []
    put:
      tags:
        - Guardian Ruins
      summary: Update a GR Site Codex Category
      description: Used to update the codex category
      operationId: updateGRCodexCategoryById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Guardian Ruins
      summary: Delete a GR Site Codex Category
      description: The response is just an empty JSON, deleting an codex category requires auth
      operationId: removeGRCodexCategoryById
      security:
        - canonnAuth: [siteDelete]
# GR Codex Data
  /grcodexdata/count:
    get:
      tags:
        - Guardian Ruins
      summary: Get a count of all GR Site Codex Data
      description: The API will respond with just a number, which is the total amount of codex data on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGRCodexDataCount
      security: []
  /grcodexdata:
    get:
      tags:
        - Guardian Ruins
      summary: Get a list of GR Site Codex Data
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGRCodexData
      security: []
    post:
      tags:
        - Guardian Ruins
      summary: Post a new GR Site Codex Data
      description: To be used to add a new codex category to the Canonn database
      operationId: submitGRCodexData
      security:
        - canonnAuth: [siteWrite]
  /grcodexdata/{id}:
    get:
      tags:
        - Guardian Ruins
      summary: Get a Single GR Site Codex Data
      description: Provide the ID to get a single codex category
      operationId: getGRCodexDataById
      security: []
    put:
      tags:
        - Guardian Ruins
      summary: Update a GR Site Codex Data
      description: Used to update the codex category
      operationId: updateGRCodexDataById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Guardian Ruins
      summary: Delete a GR Site Codex Data
      description: The response is just an empty JSON, deleting an codex category requires auth
      operationId: removeGRCodexDataById
      security:
        - canonnAuth: [siteDelete]
# GR Obelisk
  /grobelisk/count:
    get:
      tags:
        - Guardian Ruins
      summary: Get a count of all GR Site Obelisks
      description: The API will respond with just a number, which is the total amount of obelisks on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGRObelisksCount
      security: []
  /grobelisk:
    get:
      tags:
        - Guardian Ruins
      summary: Get a list of GR Site Obelisks
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGRObelisks
      security: []
    post:
      tags:
        - Guardian Ruins
      summary: Post a new GR Site Obelisk
      description: To be used to add a new obelisk to the Canonn database
      operationId: submitGRObelisk
      security:
        - canonnAuth: [siteWrite]
  /grobelisk/{id}:
    get:
      tags:
        - Guardian Ruins
      summary: Get a Single GR Site Obelisk
      description: Provide the ID to get a single obelisk
      operationId: getGRObeliskById
      security: []
    put:
      tags:
        - Guardian Ruins
      summary: Update a GR Site Obelisk
      description: Used to update the obelisk
      operationId: updateGRObeliskById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Guardian Ruins
      summary: Delete a GR Site Obelisk
      description: The response is just an empty JSON, deleting an obelisk requires auth
      operationId: removeGRObeliskById
      security:
        - canonnAuth: [siteDelete]
# GR Obelisk Group
  /grobeliskgroup/count:
    get:
      tags:
        - Guardian Ruins
      summary: Get a count of all GR Site Obelisk Groups
      description: The API will respond with just a number, which is the total amount of obelisk groups on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGRObeliskGroupsCount
      security: []
  /grobeliskgroup:
    get:
      tags:
        - Guardian Ruins
      summary: Get a list of GR Site Obelisk Groups
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGRObeliskGroups
      security: []
    post:
      tags:
        - Guardian Ruins
      summary: Post a new GR Site Obelisk Group
      description: To be used to add a new obelisk group to the Canonn database
      operationId: submitGRObeliskGroup
      security:
        - canonnAuth: [siteWrite]
  /grobeliskgroup/{id}:
    get:
      tags:
        - Guardian Ruins
      summary: Get a Single GR Site Obelisk Group
      description: Provide the ID to get a single obelisk group
      operationId: getGRObeliskGroupById
      security: []
    put:
      tags:
        - Guardian Ruins
      summary: Update a GR Site Obelisk Group
      description: Used to update the obelisk group
      operationId: updateGRObeliskGroupById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Guardian Ruins
      summary: Delete a GR Site Obelisk Group
      description: The response is just an empty JSON, deleting an obelisk group requires auth
      operationId: removeGRObeliskGroupById
      security:
        - canonnAuth: [siteDelete]
# GR Obelisk Group Report
  /grobeliskgroupreport/count:
    get:
      tags:
        - Guardian Ruin Reports
      summary: Get a count of all GR Obelisk Group Reports
      description: The API will respond with just a number, which is the total amount of reports on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGROGReportsCount
      security: []
  /grobeliskgroupreport:
    get:
      tags:
        - Guardian Ruin Reports
      summary: Get a list of GR Obelisk Group Reports
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGROGReports
      security: []
    post:
      tags:
        - Guardian Ruin Reports
      summary: Post a new GR Obelisk Group Report
      description: To be used to submit new Reports to Canonn, note that the reportStatus should always be pending
      operationId: submitGROGReport
      security: []
  /grobeliskgroupreport/{id}:
    get:
      tags:
        - Guardian Ruin Reports
      summary: Get a Single GR Obelisk Group Report
      description: Provide the ID to get a single report
      operationId: getGROGReportById
      security: []
    put:
      tags:
        - Guardian Ruin Reports
      summary: Update a GR Obelisk Group Report
      description: You do not need to send the entire report again, you can send only changed fields
      operationId: updateGROGReportById
      security: []
    delete:
      tags:
        - Guardian Ruin Reports
      summary: Delete a GR Obelisk Group Report
      description: The response is just an empty JSON, deleting a report requires auth
      operationId: removeGROGReportById
      security:
        - canonnAuth: [reportDelete]
# GR Obelisk Report
  /grobeliskreport/count:
    get:
      tags:
        - Guardian Ruin Reports
      summary: Get a count of all GR Obelisk Reports
      description: The API will respond with just a number, which is the total amount of reports on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGROReportsCount
      security: []
  /grobeliskreport:
    get:
      tags:
        - Guardian Ruin Reports
      summary: Get a list of GR Obelisk Reports
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGROReports
      security: []
    post:
      tags:
        - Guardian Ruin Reports
      summary: Post a new GR Obelisk Report
      description: To be used to submit new Reports to Canonn, note that the reportStatus should always be pending
      operationId: submitGROReport
      security: []
  /grobeliskreport/{id}:
    get:
      tags:
        - Guardian Ruin Reports
      summary: Get a Single GR Obelisk Report
      description: Provide the ID to get a single report
      operationId: getGROReportById
      security: []
    put:
      tags:
        - Guardian Ruin Reports
      summary: Update a GR Obelisk Report
      description: You do not need to send the entire report again, you can send only changed fields
      operationId: updateGROReportById
      security: []
    delete:
      tags:
        - Guardian Ruin Reports
      summary: Delete a GR Obelisk Report
      description: The response is just an empty JSON, deleting a report requires auth
      operationId: removeGROReportById
      security:
        - canonnAuth: [reportDelete]
# GR Report
  /grreport/count:
    get:
      tags:
        - Guardian Ruin Reports
      summary: Get a count of all GR Reports
      description: The API will respond with just a number, which is the total amount of reports on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGRReportsCount
      security: []
  /grreport:
    get:
      tags:
        - Guardian Ruin Reports
      summary: Get a list of GR Reports
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGRReports
      security: []
    post:
      tags:
        - Guardian Ruin Reports
      summary: Post a new GR Report
      description: To be used to submit new Reports to Canonn, note that the reportStatus should always be pending
      operationId: submitGRReport
      security: []
  /grreport/{id}:
    get:
      tags:
        - Guardian Ruin Reports
      summary: Get a Single GR Report
      description: Provide the ID to get a single report
      operationId: getGRReportById
      security: []
    put:
      tags:
        - Guardian Ruin Reports
      summary: Update a GR Report
      description: You do not need to send the entire report again, you can send only changed fields
      operationId: updateGRReportById
      security: []
    delete:
      tags:
        - Guardian Ruin Reports
      summary: Delete a GR Report
      description: The response is just an empty JSON, deleting a report requires auth
      operationId: removeGRReportById
      security:
        - canonnAuth: [reportDelete]
# GR Site
  /grsite/count:
    get:
      tags:
        - Guardian Ruins
      summary: Get a count of all GR Sites
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGRSitesCount
      security: []
  /grsite:
    get:
      tags:
        - Guardian Ruins
      summary: Get a list of GR Sites
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGRSites
      security: []
    post:
      tags:
        - Guardian Ruins
      summary: Post a new GR Site
      description: To be used to add a new site to the Canonn database, these are sites verified by Canonn
      operationId: submitGRSite
      security:
        - canonnAuth: [siteWrite]
  /grsite/{id}:
    get:
      tags:
        - Guardian Ruins
      summary: Get a Single GR Site
      description: Provide the ID to get a single site
      operationId: getGRSiteById
      security: []
    put:
      tags:
        - Guardian Ruins
      summary: Update a GR Site
      description: You do not need to send the entire site again, you can send only changed fields
      operationId: updateGRSiteById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Guardian Ruins
      summary: Delete a GR Site
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeGRSiteById
      security:
        - canonnAuth: [siteDelete]
# GR Type
  /grsitetype/count:
    get:
      tags:
        - Guardian Ruins
      summary: Get a count of all GR Site Types
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGRSiteTypesCount
      security: []
  /grsitetype:
    get:
      tags:
        - Guardian Ruins
      summary: Get a list of GR Site Types
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGRSiteTypes
      security: []
    post:
      tags:
        - Guardian Ruins
      summary: Post a new GR Site Type
      description: To be used to add a new site type to the Canonn database
      operationId: submitGRSiteType
      security:
        - canonnAuth: [siteWrite]
  /grsitetype/{id}:
    get:
      tags:
        - Guardian Ruins
      summary: Get a Single GR Site Type
      description: Provide the ID to get a single site
      operationId: getGRSiteTypeById
      security: []
    put:
      tags:
        - Guardian Ruins
      summary: Update a GR Site Type
      description: The type is set by Canonn as a whole based on the layout
      operationId: updateGRSiteTypeById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Guardian Ruins
      summary: Delete a GR Site Type
      description: The response is just an empty JSON, deleting a site type requires auth
      operationId: removeGRSiteTypeById
      security:
        - canonnAuth: [siteDelete]
# GS Active Group
  /gsactivegroup/count:
    get:
      tags:
        - Guardian Structures
      summary: Get a count of all GS Active Groups
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGSSiteActiveGroupsCount
      security: []
  /gsactivegroup:
    get:
      tags:
        - Guardian Structures
      summary: Get a list of GS Site Active Groups
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGSSiteActiveGroups
      security: []
    post:
      tags:
        - Guardian Structures
      summary: Post a new GS Site Active Group
      description: To be used to add a new site to the Canonn database, these are sites verified by Canonn
      operationId: submitGSSiteActiveGroup
      security:
        - canonnAuth: [siteWrite]
  /gsactivegroup/{id}:
    get:
      tags:
        - Guardian Structures
      summary: Get a Single GS Site Active Group
      description: Provide the ID to get a single site
      operationId: getGSSiteActiveGroupById
      security: []
    put:
      tags:
        - Guardian Structures
      summary: Update a GS Site Active Group
      description: Used to change the active group, be sure there are no duplicates
      operationId: updateGSSiteActiveGroupById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Guardian Structures
      summary: Delete a GS Site Active Group
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeGSSiteActiveGroupById
      security:
        - canonnAuth: [siteDelete]
# GS Active Obelisk
  /gsactiveobelisk/count:
    get:
      tags:
        - Guardian Structures
      summary: Get a count of all GS Active Obelisks
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGSSiteActiveObelisksCount
      security: []
  /gsactiveobelisk:
    get:
      tags:
        - Guardian Structures
      summary: Get a list of GS Site Active Obelisks
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGSSiteActiveObelisks
      security: []
    post:
      tags:
        - Guardian Structures
      summary: Post a new GS Site Active Obelisk
      description: To be used to add a new site to the Canonn database, these are sites verified by Canonn
      operationId: submitGSSiteActiveObelisk
      security:
        - canonnAuth: [siteWrite]
  /gsactiveobelisk/{id}:
    get:
      tags:
        - Guardian Structures
      summary: Get a Single GS Site Active Obelisk
      description: Provide the ID to get a single site
      operationId: getGSSiteActiveObeliskById
      security: []
    put:
      tags:
        - Guardian Structures
      summary: Update a GS Site Active Obelisk
      description: Used to change the active obelisk, be sure there are no duplicates
      operationId: updateGSSiteActiveObeliskById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Guardian Structures
      summary: Delete a GS Site Active Obelisk
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeGSSiteActiveObeliskById
      security:
        - canonnAuth: [siteDelete]
# GS Artifact
  /gsartifact/count:
    get:
      tags:
        - Guardian Structures
      summary: Get a count of all GS Site Artifacts
      description: The API will respond with just a number, which is the total amount of artifacts on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGSArtifactsCount
      security: []
  /gsartifact:
    get:
      tags:
        - Guardian Structures
      summary: Get a list of GS Site Artifacts
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGSArtifacts
      security: []
    post:
      tags:
        - Guardian Structures
      summary: Post a new GS Site Artifact
      description: To be used to add a new artifact to the Canonn database
      operationId: submitGSArtifact
      security:
        - canonnAuth: [siteWrite]
  /gsartifact/{id}:
    get:
      tags:
        - Guardian Structures
      summary: Get a Single GS Site Artifact
      description: Provide the ID to get a single artifact
      operationId: getGSArtifactById
      security: []
    put:
      tags:
        - Guardian Structures
      summary: Update a GS Site Artifact
      description: Used to update the artifact
      operationId: updateGSArtifactById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Guardian Structures
      summary: Delete a GS Site Artifact
      description: The response is just an empty JSON, deleting an artifact requires auth
      operationId: removeGSArtifactById
      security:
        - canonnAuth: [siteDelete]
# GS Codex Category
  /gscodexcategory/count:
    get:
      tags:
        - Guardian Structures
      summary: Get a count of all GS Site Codex Categories
      description: The API will respond with just a number, which is the total amount of codex categories on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGSCodexCategoriesCount
      security: []
  /gscodexcategory:
    get:
      tags:
        - Guardian Structures
      summary: Get a list of GS Site Codex Categories
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGSCodexCategories
      security: []
    post:
      tags:
        - Guardian Structures
      summary: Post a new GS Site Codex Category
      description: To be used to add a new codex category to the Canonn database
      operationId: submitGSCodexCategory
      security:
        - canonnAuth: [siteWrite]
  /gscodexcategory/{id}:
    get:
      tags:
        - Guardian Structures
      summary: Get a Single GS Site Codex Category
      description: Provide the ID to get a single codex category
      operationId: getGSCodexCategoryById
      security: []
    put:
      tags:
        - Guardian Structures
      summary: Update a GS Site Codex Category
      description: Used to update the codex category
      operationId: updateGSCodexCategoryById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Guardian Structures
      summary: Delete a GS Site Codex Category
      description: The response is just an empty JSON, deleting an codex category requires auth
      operationId: removeGSCodexCategoryById
      security:
        - canonnAuth: [siteDelete]
# GS Codex Data
  /gscodexdata/count:
    get:
      tags:
        - Guardian Structures
      summary: Get a count of all GS Site Codex Data
      description: The API will respond with just a number, which is the total amount of codex data on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGSCodexDataCount
      security: []
  /gscodexdata:
    get:
      tags:
        - Guardian Structures
      summary: Get a list of GS Site Codex Data
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGSCodexData
      security: []
    post:
      tags:
        - Guardian Structures
      summary: Post a new GS Site Codex Data
      description: To be used to add a new codex category to the Canonn database
      operationId: submitGSCodexData
      security:
        - canonnAuth: [siteWrite]
  /gscodexdata/{id}:
    get:
      tags:
        - Guardian Structures
      summary: Get a Single GS Site Codex Data
      description: Provide the ID to get a single codex category
      operationId: getGSCodexDataById
      security: []
    put:
      tags:
        - Guardian Structures
      summary: Update a GS Site Codex Data
      description: Used to update the codex category
      operationId: updateGSCodexDataById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Guardian Structures
      summary: Delete a GS Site Codex Data
      description: The response is just an empty JSON, deleting an codex category requires auth
      operationId: removeGSCodexDataById
      security:
        - canonnAuth: [siteDelete]
# GS Obelisk
  /gsobelisk/count:
    get:
      tags:
        - Guardian Structures
      summary: Get a count of all GS Site Obelisks
      description: The API will respond with just a number, which is the total amount of obelisks on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGSObelisksCount
      security: []
  /gsobelisk:
    get:
      tags:
        - Guardian Structures
      summary: Get a list of GS Site Obelisks
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGSObelisks
      security: []
    post:
      tags:
        - Guardian Structures
      summary: Post a new GS Site Obelisk
      description: To be used to add a new obelisk to the Canonn database
      operationId: submitGSObelisk
      security:
        - canonnAuth: [siteWrite]
  /gsobelisk/{id}:
    get:
      tags:
        - Guardian Structures
      summary: Get a Single GS Site Obelisk
      description: Provide the ID to get a single obelisk
      operationId: getGSObeliskById
      security: []
    put:
      tags:
        - Guardian Structures
      summary: Update a GS Site Obelisk
      description: Used to update the obelisk
      operationId: updateGSObeliskById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Guardian Structures
      summary: Delete a GS Site Obelisk
      description: The response is just an empty JSON, deleting an obelisk requires auth
      operationId: removeGSObeliskById
      security:
        - canonnAuth: [siteDelete]
# GS Obelisk Group
  /gsobeliskgroup/count:
    get:
      tags:
        - Guardian Structures
      summary: Get a count of all GS Site Obelisk Groups
      description: The API will respond with just a number, which is the total amount of obelisk groups on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGSObeliskGroupsCount
      security: []
  /gsobeliskgroup:
    get:
      tags:
        - Guardian Structures
      summary: Get a list of GS Site Obelisk Groups
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGSObeliskGroups
      security: []
    post:
      tags:
        - Guardian Structures
      summary: Post a new GS Site Obelisk Group
      description: To be used to add a new obelisk group to the Canonn database
      operationId: submitGSObeliskGroup
      security:
        - canonnAuth: [siteWrite]
  /gsobeliskgroup/{id}:
    get:
      tags:
        - Guardian Structures
      summary: Get a Single GS Site Obelisk Group
      description: Provide the ID to get a single obelisk group
      operationId: getGSObeliskGroupById
      security: []
    put:
      tags:
        - Guardian Structures
      summary: Update a GS Site Obelisk Group
      description: Used to update the obelisk group
      operationId: updateGSObeliskGroupById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Guardian Structures
      summary: Delete a GS Site Obelisk Group
      description: The response is just an empty JSON, deleting an obelisk group requires auth
      operationId: removeGSObeliskGroupById
      security:
        - canonnAuth: [siteDelete]
# GS Obelisk Group Report
  /gsobeliskgroupreport/count:
    get:
      tags:
        - Guardian Structure Reports
      summary: Get a count of all GS Obelisk Group Reports
      description: The API will respond with just a number, which is the total amount of reports on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGSOGReportsCount
      security: []
  /gsobeliskgroupreport:
    get:
      tags:
        - Guardian Structure Reports
      summary: Get a list of GS Obelisk Group Reports
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGSOGReports
      security: []
    post:
      tags:
        - Guardian Structure Reports
      summary: Post a new GS Obelisk Group Report
      description: To be used to submit new Reports to Canonn, note that the reportStatus should always be pending
      operationId: submitGSOGReport
      security: []
  /gsobeliskgroupreport/{id}:
    get:
      tags:
        - Guardian Structure Reports
      summary: Get a Single GS Obelisk Group Report
      description: Provide the ID to get a single report
      operationId: getGSOGReportById
      security: []
    put:
      tags:
        - Guardian Structure Reports
      summary: Update a GS Obelisk Group Report
      description: You do not need to send the entire report again, you can send only changed fields
      operationId: updateGSOGReportById
      security: []
    delete:
      tags:
        - Guardian Structure Reports
      summary: Delete a GS Obelisk Group Report
      description: The response is just an empty JSON, deleting a report requires auth
      operationId: removeGSOGReportById
      security:
        - canonnAuth: [reportDelete]
# GS Obelisk Report
  /gsobeliskreport/count:
    get:
      tags:
        - Guardian Structure Reports
      summary: Get a count of all GS Obelisk Reports
      description: The API will respond with just a number, which is the total amount of reports on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGSOReportsCount
      security: []
  /gsobeliskreport:
    get:
      tags:
        - Guardian Structure Reports
      summary: Get a list of GS Obelisk Reports
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGSOReports
      security: []
    post:
      tags:
        - Guardian Structure Reports
      summary: Post a new GS Obelisk Report
      description: To be used to submit new Reports to Canonn, note that the reportStatus should always be pending
      operationId: submitGSOReport
      security: []
  /gsobeliskreport/{id}:
    get:
      tags:
        - Guardian Structure Reports
      summary: Get a Single GS Obelisk Report
      description: Provide the ID to get a single report
      operationId: getGSOReportById
      security: []
    put:
      tags:
        - Guardian Structure Reports
      summary: Update a GS Obelisk Report
      description: You do not need to send the entire report again, you can send only changed fields
      operationId: updateGSOReportById
      security: []
    delete:
      tags:
        - Guardian Structure Reports
      summary: Delete a GS Obelisk Report
      description: The response is just an empty JSON, deleting a report requires auth
      operationId: removeGSOReportById
      security:
        - canonnAuth: [reportDelete]
# GS Report
  /gsreport/count:
    get:
      tags:
        - Guardian Structure Reports
      summary: Get a count of all GS Reports
      description: The API will respond with just a number, which is the total amount of reports on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGSReportsCount
      security: []
  /gsreport:
    get:
      tags:
        - Guardian Structure Reports
      summary: Get a list of GS Reports
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGSReports
      security: []
    post:
      tags:
        - Guardian Structure Reports
      summary: Post a new GS Report
      description: To be used to submit new Reports to Canonn, note that the reportStatus should always be pending
      operationId: submitGSReport
      security: []
  /gsreport/{id}:
    get:
      tags:
        - Guardian Structure Reports
      summary: Get a Single GS Report
      description: Provide the ID to get a single report
      operationId: getGSReportById
      security: []
    put:
      tags:
        - Guardian Structure Reports
      summary: Update a GS Report
      description: You do not need to send the entire report again, you can send only changed fields
      operationId: updateGSReportById
      security: []
    delete:
      tags:
        - Guardian Structure Reports
      summary: Delete a GS Report
      description: The response is just an empty JSON, deleting a report requires auth
      operationId: removeGSReportById
      security:
        - canonnAuth: [reportDelete]
# GS Site
  /gssite/count:
    get:
      tags:
        - Guardian Structures
      summary: Get a count of all GS Sites
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGSSitesCount
      security: []
  /gssite:
    get:
      tags:
        - Guardian Structures
      summary: Get a list of GS Sites
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGSSites
      security: []
    post:
      tags:
        - Guardian Structures
      summary: Post a new GS Site
      description: To be used to add a new site to the Canonn database, these are sites verified by Canonn
      operationId: submitGSSite
      security:
        - canonnAuth: [siteWrite]
  /gssite/{id}:
    get:
      tags:
        - Guardian Structures
      summary: Get a Single GS Site
      description: Provide the ID to get a single site
      operationId: getGSSiteById
      security: []
    put:
      tags:
        - Guardian Structures
      summary: Update a GS Site
      description: You do not need to send the entire site again, you can send only changed fields
      operationId: updateGSSiteById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Guardian Structures
      summary: Delete a GS Site
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeGSSiteById
      security:
        - canonnAuth: [siteDelete]
# GS Type
  /gssitetype/count:
    get:
      tags:
        - Guardian Structures
      summary: Get a count of all GS Site Types
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGSSiteTypesCount
      security: []
  /gssitetype:
    get:
      tags:
        - Guardian Structures
      summary: Get a list of GS Site Types
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGSSiteTypes
      security: []
    post:
      tags:
        - Guardian Structures
      summary: Post a new GS Site Type
      description: To be used to add a new site type to the Canonn database
      operationId: submitGSSiteType
      security:
        - canonnAuth: [siteWrite]
  /gssitetype/{id}:
    get:
      tags:
        - Guardian Structures
      summary: Get a Single GS Site Type
      description: Provide the ID to get a single site
      operationId: getGSSiteTypeById
      security: []
    put:
      tags:
        - Guardian Structures
      summary: Update a GS Site Type
      description: The type is set by Canonn as a whole based on the layout
      operationId: updateGSSiteTypeById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Guardian Structures
      summary: Delete a GS Site Type
      description: The response is just an empty JSON, deleting a site type requires auth
      operationId: removeGSSiteTypeById
      security:
        - canonnAuth: [siteDelete]
# GY Report
  /gyreport/count:
    get:
      tags:
        - Geyser Reports
      summary: Get a count of all GY Reports
      description: The API will respond with just a number, which is the total amount of reports on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGYReportsCount
      security: []
  /gyreport:
    get:
      tags:
        - Geyser Reports
      summary: Get a list of GY Reports
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGYReports
      security: []
    post:
      tags:
        - Geyser Reports
      summary: Post a new GY Report
      description: To be used to submit new Reports to Canonn, note that the reportStatus should always be pending
      operationId: submitGYReport
      security: []
  /gyreport/{id}:
    get:
      tags:
        - Geyser Reports
      summary: Get a Single GY Report
      description: Provide the ID to get a single report
      operationId: getGYReportById
      security: []
    put:
      tags:
        - Geyser Reports
      summary: Update a GY Report
      description: You do not need to send the entire report again, you can send only changed fields
      operationId: updateGYReportById
      security: []
    delete:
      tags:
        - Geyser Reports
      summary: Delete a GY Report
      description: The response is just an empty JSON, deleting a report requires auth
      operationId: removeGYReportById
      security:
        - canonnAuth: [reportDelete]
# GY Site
  /gysite/count:
    get:
      tags:
        - Geysers
      summary: Get a count of all GY Sites
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGYSitesCount
      security: []
  /gysite:
    get:
      tags:
        - Geysers
      summary: Get a list of GY Sites
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGYSites
      security: []
    post:
      tags:
        - Geysers
      summary: Post a new GY Site
      description: To be used to add a new site to the Canonn database, these are sites verified by Canonn
      operationId: submitGYSite
      security:
        - canonnAuth: [siteWrite]
  /gysite/{id}:
    get:
      tags:
        - Geysers
      summary: Get a Single GY Site
      description: Provide the ID to get a single site
      operationId: getGYSiteById
      security: []
    put:
      tags:
        - Geysers
      summary: Update a GY Site
      description: You do not need to send the entire site again, you can send only changed fields
      operationId: updateGYSiteById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Geysers
      summary: Delete a GY Site
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeGYSiteById
      security:
        - canonnAuth: [siteDelete]
# GY Type
  /gysitetype/count:
    get:
      tags:
        - Geysers
      summary: Get a count of all GY Site Types
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getGYSiteTypesCount
      security: []
  /gysitetype:
    get:
      tags:
        - Geysers
      summary: Get a list of GY Site Types
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getGYSiteTypes
      security: []
    post:
      tags:
        - Geysers
      summary: Post a new GY Site Type
      description: To be used to add a new site type to the Canonn database
      operationId: submitGYSiteType
      security:
        - canonnAuth: [siteWrite]
  /gysitetype/{id}:
    get:
      tags:
        - Geysers
      summary: Get a Single GY Site Type
      description: Provide the ID to get a single site
      operationId: getGYSiteTypeById
      security: []
    put:
      tags:
        - Geysers
      summary: Update a GY Site Type
      description: The type should match those used by EDSM if appropriate
      operationId: updateGYSiteTypeById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Geysers
      summary: Delete a GY Site Type
      description: The response is just an empty JSON, deleting a site type requires auth
      operationId: removeGYSiteTypeById
      security:
        - canonnAuth: [siteDelete]
# HD Report
  /hdreport/count:
    get:
      tags:
        - Hyperdiction Reports
      summary: Get a count of all HD Reports
      description: The API will respond with just a number, which is the total amount of reports on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getHDReportsCount
      security: []
  /hdreport:
    get:
      tags:
        - Hyperdiction Reports
      summary: Get a list of HD Reports
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getHDReports
      security: []
    post:
      tags:
        - Hyperdiction Reports
      summary: Post a new HD Report
      description: To be used to add a new report to the Canonn database
      operationId: submitHDReport
      security: []
  /hdreport/{id}:
    get:
      tags:
        - Hyperdiction Reports
      summary: Get a Single HD Report
      description: Provide the ID to get a single report
      operationId: getHDReportById
      security: []
    put:
      tags:
        - Hyperdiction Reports
      summary: Update a HD Report
      description: You do not need to send the entire report again, you can send only changed fields
      operationId: updateHDReportById
      security: []
    delete:
      tags:
        - Hyperdiction Reports
      summary: Delete a HD Report
      description: The response is just an empty JSON, deleting a report requires auth
      operationId: removeHDReportById
      security:
        - canonnAuth: [reportDelete]
# HD Site
  /hdsite/count:
    get:
      tags:
        - Hyperdictions
      summary: Get a count of all HD Sites
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getHDSitesCount
      security: []
  /hdsite:
    get:
      tags:
        - Hyperdictions
      summary: Get a list of HD Sites
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getHDSites
      security: []
    post:
      tags:
        - Hyperdictions
      summary: Post a new HD Site
      description: To be used to add a new site to the Canonn database, these are sites verified by Canonn
      operationId: submitHDSite
      security:
        - canonnAuth: [siteWrite]
  /hdsite/{id}:
    get:
      tags:
        - Hyperdictions
      summary: Get a Single HD Site
      description: Provide the ID to get a single site
      operationId: getHDSiteById
      security: []
    put:
      tags:
        - Hyperdictions
      summary: Update a HD Site
      description: You do not need to send the entire site again, you can send only changed fields
      operationId: updateHDSiteById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Hyperdictions
      summary: Delete a HD Site
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeHDSiteById
      security:
        - canonnAuth: [siteDelete]
# Journal Data

# Location
  /location/count:
    get:
      tags:
        - Locations
      summary: Get a count of all Locations
      description: The API will respond with just a number, which is the total amount of locations on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getLocationsCount
      security: []
  /location:
    get:
      tags:
        - Locations
      summary: Get a list of Locations
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getLocations
      security: []
    post:
      tags:
        - Locations
      summary: Post a new Location
      description: To be used to add a new location to the Canonn database
      operationId: submitLocation
      security:
        - canonnAuth: [locationWrite]
  /location/{id}:
    get:
      tags:
        - Locations
      summary: Get a Single Location
      description: Provide the ID to get a single location
      operationId: getLocationById
      security: []
    put:
      tags:
        - Locations
      summary: Update a Location
      description: You do not need to send the entire site again, you can send only changed fields
      operationId: updateLocationById
      security:
        - canonnAuth: [locationWrite]
    delete:
      tags:
        - Locations
      summary: Delete a Location
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeLocationById
      security:
        - canonnAuth: [locationDelete]
# LS Report
  /lsreport/count:
    get:
      tags:
        - Lava Spout Reports
      summary: Get a count of all LS Reports
      description: The API will respond with just a number, which is the total amount of reports on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getLSReportsCount
      security: []
  /lsreport:
    get:
      tags:
        - Lava Spout Reports
      summary: Get a list of LS Reports
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getLSReports
      security: []
    post:
      tags:
        - Lava Spout Reports
      summary: Post a new LS Report
      description: To be used to submit new Reports to Canonn, note that the reportStatus should always be pending
      operationId: submitLSReport
      security: []
  /lsreport/{id}:
    get:
      tags:
        - Lava Spout Reports
      summary: Get a Single LS Report
      description: Provide the ID to get a single report
      operationId: getLSReportById
      security: []
    put:
      tags:
        - Lava Spout Reports
      summary: Update a LS Report
      description: You do not need to send the entire report again, you can send only changed fields
      operationId: updateLSReportById
      security: []
    delete:
      tags:
        - Lava Spout Reports
      summary: Delete a LS Report
      description: The response is just an empty JSON, deleting a report requires auth
      operationId: removeLSReportById
      security:
        - canonnAuth: [reportDelete]
# LS Site
  /lssite/count:
    get:
      tags:
        - Lava Spouts
      summary: Get a count of all LS Sites
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getLSSitesCount
      security: []
  /lssite:
    get:
      tags:
        - Lava Spouts
      summary: Get a list of LS Sites
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getLSSites
      security: []
    post:
      tags:
        - Lava Spouts
      summary: Post a new LS Site
      description: To be used to add a new site to the Canonn database, these are sites verified by Canonn
      operationId: submitLSSite
      security:
        - canonnAuth: [siteWrite]
  /lssite/{id}:
    get:
      tags:
        - Lava Spouts
      summary: Get a Single LS Site
      description: Provide the ID to get a single site
      operationId: getLSSiteById
      security: []
    put:
      tags:
        - Lava Spouts
      summary: Update a LS Site
      description: You do not need to send the entire site again, you can send only changed fields
      operationId: updateLSSiteById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Lava Spouts
      summary: Delete a LS Site
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeLSSiteById
      security:
        - canonnAuth: [siteDelete]
# MS Report
  /msreport/count:
    get:
      tags:
        - Megaship Reports
      summary: Get a count of all MS Reports
      description: The API will respond with just a number, which is the total amount of reports on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getMSReportsCount
      security: []
  /msreport:
    get:
      tags:
        - Megaship Reports
      summary: Get a list of MS Reports
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getMSReports
      security: []
    post:
      tags:
        - Megaship Reports
      summary: Post a new MS Report
      description: To be used to submit new Reports to Canonn, note that the reportStatus should always be pending
      operationId: submitMSReport
      security: []
  /msreport/{id}:
    get:
      tags:
        - Megaship Reports
      summary: Get a Single MS Report
      description: Provide the ID to get a single report
      operationId: getMSReportById
      security: []
    put:
      tags:
        - Megaship Reports
      summary: Update a MS Report
      description: You do not need to send the entire report again, you can send only changed fields
      operationId: updateMSReportById
      security: []
    delete:
      tags:
        - Megaship Reports
      summary: Delete a MS Report
      description: The response is just an empty JSON, deleting a report requires auth
      operationId: removeMSReportById
      security:
        - canonnAuth: [reportDelete]
# MS Site
  /mssite/count:
    get:
      tags:
        - Megaships
      summary: Get a count of all MS Sites
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getMSSitesCount
      security: []
  /mssite:
    get:
      tags:
        - Megaships
      summary: Get a list of MS Sites
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getMSSites
      security: []
    post:
      tags:
        - Megaships
      summary: Post a new MS Site
      description: To be used to add a new site to the Canonn database, these are sites verified by Canonn
      operationId: submitMSSite
      security:
        - canonnAuth: [siteWrite]
  /mssite/{id}:
    get:
      tags:
        - Megaships
      summary: Get a Single MS Site
      description: Provide the ID to get a single site
      operationId: getMSSiteById
      security: []
    put:
      tags:
        - Megaships
      summary: Update a MS Site
      description: You do not need to send the entire site again, you can send only changed fields
      operationId: updateMSSiteById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Megaships
      summary: Delete a MS Site
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeMSSiteById
      security:
        - canonnAuth: [siteDelete]
# MS Type
  /mssitetype/count:
    get:
      tags:
        - Megaships
      summary: Get a count of all MS Site Types
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getMSSiteTypesCount
      security: []
  /mssitetype:
    get:
      tags:
        - Megaships
      summary: Get a list of MS Site Types
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getMSSiteTypes
      security: []
    post:
      tags:
        - Megaships
      summary: Post a new MS Site Type
      description: To be used to add a new site type to the Canonn database
      operationId: submitMSSiteType
      security:
        - canonnAuth: [siteWrite]
  /mssitetype/{id}:
    get:
      tags:
        - Megaships
      summary: Get a Single MS Site Type
      description: Provide the ID to get a single site
      operationId: getMSSiteTypeById
      security: []
    put:
      tags:
        - Megaships
      summary: Update a MS Site Type
      description: The type should match those used by EDSM if appropriate
      operationId: updateMSSiteTypeById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Megaships
      summary: Delete a MS Site Type
      description: The response is just an empty JSON, deleting a site type requires auth
      operationId: removeMSSiteTypeById
      security:
        - canonnAuth: [siteDelete]
# NHSS Top CMDR Kill
  /nhsstopcmdrsbykill/count:
    get:
      tags:
        - CMDRs
      summary: Get a count of all NHSS Top CMDR Kill Stats
      description: The API will respond with just a number, which is the total amount of kill stats on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getNHSSTopCMDRsByKillCount
      security: []
  /nhsstopcmdrsbykill:
    get:
      tags:
        - CMDRs
      summary: Get a list of NHSS Top CMDR Kill Stats
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getNHSSTopCMDRsByKills
      security: []
    post:
      tags:
        - CMDRs
      summary: Post a new NHSS Top CMDR Kill Stat
      description: Kill Stats by CMDR for Non-Human Signal Sources
      operationId: submitNHSSTopCMDRsByKill
      security:
        - canonnAuth: [cmdrWrite]
  /nhsstopcmdrsbykill/{id}:
    get:
      tags:
        - CMDRs
      summary: Get a Single NHSS Top CMDR Kill Stat
      description: Provide the ID to get a single stat
      operationId: getNHSSTopCMDRsByKillById
      security: []
    put:
      tags:
        - CMDRs
      summary: Update a NHSS Top CMDR Kill Stat
      description: You do not need to send the entire stat again, you can send only changed fields
      operationId: updateNHSSTopCMDRsByKillById
      security:
        - canonnAuth: [cmdrWrite]
    delete:
      tags:
        - CMDRs
      summary: Delete a NHSS Top CMDR Kill Stat
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeNHSSTopCMDRsByKillById
      security:
        - canonnAuth: [cmdrDelete]
# Ring
  /ring/count:
    get:
      tags:
        - Rings
      summary: Get a count of all Rings
      description: The API will respond with just a number, which is the total amount of rings on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getRingsCount
      security: []
  /ring:
    get:
      tags:
        - Rings
      summary: Get a list of Rings
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getRings
      security: []
    post:
      tags:
        - Rings
      summary: Post a new Ring
      description: To be used to add a new ring to the Canonn database
      operationId: submitRing
      security:
        - canonnAuth: [locationWrite]
  /ring/{id}:
    get:
      tags:
        - Rings
      summary: Get a Single Ring
      description: Provide the ID to get a single ring
      operationId: getRingById
      security: []
    put:
      tags:
        - Rings
      summary: Update a Ring
      description: You do not need to send the entire site again, you can send only changed fields
      operationId: updateRingById
      security:
        - canonnAuth: [locationWrite]
    delete:
      tags:
        - Rings
      summary: Delete a Ring
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeRingById
      security:
        - canonnAuth: [locationDelete]
# Ring Type
  /ringtype/count:
    get:
      tags:
        - Rings
      summary: Get a count of all Ring Types
      description: The API will respond with just a number, which is the total amount of ring types on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getRingTypesCount
      security: []
  /ringtype:
    get:
      tags:
        - Rings
      summary: Get a list of Ring Types
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getRingTypes
      security: []
    post:
      tags:
        - Rings
      summary: Post a new Ring Type
      description: To be used to add a new ring type to the Canonn database
      operationId: submitRing
      security:
        - canonnAuth: [locationWrite]
  /ringtype/{id}:
    get:
      tags:
        - Rings
      summary: Get a Single Ring Type
      description: Provide the ID to get a single ring
      operationId: getRingTypeById
      security: []
    put:
      tags:
        - Rings
      summary: Update a Ring Type
      description: Ring Type should match types used by EDSM
      operationId: updateRingTypeById
      security:
        - canonnAuth: [locationWrite]
    delete:
      tags:
        - Rings
      summary: Delete a Ring Type
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeRingTypeById
      security:
        - canonnAuth: [locationDelete]
# System
  /system/count:
    get:
      tags:
        - Systems
      summary: Get a count of all Systems
      description: The API will respond with just a number, which is the total amount of systems on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getSystemsCount
      security: []
  /system:
    get:
      tags:
        - Systems
      summary: Get a list of Systems
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getSystems
      security: []
    post:
      tags:
        - Systems
      summary: Post a new System
      description: To be used to add a new system to the Canonn database
      operationId: submitSystem
      security:
        - canonnAuth: [locationWrite]
  /system/{id}:
    get:
      tags:
        - Systems
      summary: Get a Single System
      description: Provide the ID to get a single system
      operationId: getSystemById
      security: []
    put:
      tags:
        - Systems
      summary: Update a System
      description: You do not need to send the entire site again, you can send only changed fields
      operationId: updateSystemById
      security:
        - canonnAuth: [locationWrite]
    delete:
      tags:
        - Systems
      summary: Delete a System
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeSystemById
      security:
        - canonnAuth: [locationDelete]
# TB Report
  /tbreport/count:
    get:
      tags:
        - Thargoid Barnacle Reports
      summary: Get a count of all TB Reports
      description: The API will respond with just a number, which is the total amount of reports on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getTBReportsCount
      security: []
  /tbreport:
    get:
      tags:
        - Thargoid Barnacle Reports
      summary: Get a list of TB Reports
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getTBReports
      security: []
    post:
      tags:
        - Thargoid Barnacle Reports
      summary: Post a new TB Report
      description: To be used to submit new Reports to Canonn, note that the reportStatus should always be pending
      operationId: submitTBReport
      security: []
  /tbreport/{id}:
    get:
      tags:
        - Thargoid Barnacle Reports
      summary: Get a Single TB Report
      description: Provide the ID to get a single report
      operationId: getTBReportById
      security: []
    put:
      tags:
        - Thargoid Barnacle Reports
      summary: Update a TB Report
      description: You do not need to send the entire report again, you can send only changed fields
      operationId: updateTBReportById
      security: []
    delete:
      tags:
        - Thargoid Barnacle Reports
      summary: Delete a TB Report
      description: The response is just an empty JSON, deleting a report requires auth
      operationId: removeTBReportById
      security:
        - canonnAuth: [reportDelete]
# TB Site
  /tbsite/count:
    get:
      tags:
        - Thargoid Barnacles
      summary: Get a count of all TB Sites
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getTBSitesCount
      security: []
  /tbsite:
    get:
      tags:
        - Thargoid Barnacles
      summary: Get a list of TB Sites
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getTBSites
      security: []
    post:
      tags:
        - Thargoid Barnacles
      summary: Post a new TB Site
      description: To be used to add a new site to the Canonn database, these are sites verified by Canonn
      operationId: submitTBSite
      security:
        - canonnAuth: [siteWrite]
  /tbsite/{id}:
    get:
      tags:
        - Thargoid Barnacles
      summary: Get a Single TB Site
      description: Provide the ID to get a single site
      operationId: getTBSiteById
      security: []
    put:
      tags:
        - Thargoid Barnacles
      summary: Update a TB Site
      description: You do not need to send the entire site again, you can send only changed fields
      operationId: updateTBSiteById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Thargoid Barnacles
      summary: Delete a TB Site
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeTBSiteById
      security:
        - canonnAuth: [siteDelete]
# TB Type
  /tbsitetype/count:
    get:
      tags:
        - Thargoid Barnacles
      summary: Get a count of all TB Site Types
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getTBSiteTypesCount
      security: []
  /tbsitetype:
    get:
      tags:
        - Thargoid Barnacles
      summary: Get a list of TB Site Types
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getTBSiteTypes
      security: []
    post:
      tags:
        - Thargoid Barnacles
      summary: Post a new TB Site Type
      description: To be used to add a new site type to the Canonn database
      operationId: submitTBSiteType
      security:
        - canonnAuth: [siteWrite]
  /tbsitetype/{id}:
    get:
      tags:
        - Thargoid Barnacles
      summary: Get a Single TB Site Type
      description: Provide the ID to get a single site
      operationId: getTBSiteTypeById
      security: []
    put:
      tags:
        - Thargoid Barnacles
      summary: Update a TB Site Type
      description: Used to update the type name
      operationId: updateTBSiteTypeById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Thargoid Barnacles
      summary: Delete a TB Site Type
      description: The response is just an empty JSON, deleting a site type requires auth
      operationId: removeTBSiteTypeById
      security:
        - canonnAuth: [siteDelete]
# TS Report
  /tsreport/count:
    get:
      tags:
        - Thargoid Structure Reports
      summary: Get a count of all TS Reports
      description: The API will respond with just a number, which is the total amount of reports on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getTSReportsCount
      security: []
  /tsreport:
    get:
      tags:
        - Thargoid Structure Reports
      summary: Get a list of TS Reports
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getTSReports
      security: []
    post:
      tags:
        - Thargoid Structure Reports
      summary: Post a new TS Report
      description: To be used to submit new Reports to Canonn, note that the reportStatus should always be pending
      operationId: submitTSReport
      security: []
  /tsreport/{id}:
    get:
      tags:
        - Thargoid Structure Reports
      summary: Get a Single TS Report
      description: Provide the ID to get a single report
      operationId: getTSReportById
      security: []
    put:
      tags:
        - Thargoid Structure Reports
      summary: Update a TS Report
      description: You do not need to send the entire report again, you can send only changed fields
      operationId: updateTSReportById
      security: []
    delete:
      tags:
        - Thargoid Structure Reports
      summary: Delete a TS Report
      description: The response is just an empty JSON, deleting a report requires auth
      operationId: removeTSReportById
      security:
        - canonnAuth: [reportDelete]
# TS Site
  /tssite/count:
    get:
      tags:
        - Thargoid Structures
      summary: Get a count of all TS Sites
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getTSSitesCount
      security: []
  /tssite:
    get:
      tags:
        - Thargoid Structures
      summary: Get a list of TS Sites
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getTSSites
      security: []
    post:
      tags:
        - Thargoid Structures
      summary: Post a new TS Site
      description: To be used to add a new site to the Canonn database, these are sites verified by Canonn
      operationId: submitTSSite
      security:
        - canonnAuth: [siteWrite]
  /tssite/{id}:
    get:
      tags:
        - Thargoid Structures
      summary: Get a Single TS Site
      description: Provide the ID to get a single site
      operationId: getTSSiteById
      security: []
    put:
      tags:
        - Thargoid Structures
      summary: Update a TS Site
      description: You do not need to send the entire site again, you can send only changed fields
      operationId: updateTSSiteById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Thargoid Structures
      summary: Delete a TS Site
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeTSSiteById
      security:
        - canonnAuth: [siteDelete]
# TS Status
  /tssitetype/count:
    get:
      tags:
        - Thargoid Structure
      summary: Get a count of all TS Site Statuses
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getTSSiteStatusesCount
      security: []
  /tssitetype:
    get:
      tags:
        - Thargoid Structure
      summary: Get a list of TS Site Statuses
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getTSSiteStatuses
      security: []
    post:
      tags:
        - Thargoid Structure
      summary: Post a new TS Site Status
      description: To be used to add a new site type to the Canonn database
      operationId: submitTSSiteStatus
      security:
        - canonnAuth: [siteWrite]
  /tssitetype/{id}:
    get:
      tags:
        - Thargoid Structure
      summary: Get a Single TS Site Status
      description: Provide the ID to get a single site
      operationId: getTSSiteStatusById
      security: []
    put:
      tags:
        - Thargoid Structure
      summary: Update a TS Site Status
      description: The type should match how the site reacts, and if you can access the structure
      operationId: updateTSSiteStatusById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Thargoid Structure
      summary: Delete a TS Site Status
      description: The response is just an empty JSON, deleting a site type requires auth
      operationId: removeTSSiteStatusById
      security:
        - canonnAuth: [siteDelete]
# TW Report
  /twreport/count:
    get:
      tags:
        - Tube Worm Reports
      summary: Get a count of all TW Reports
      description: The API will respond with just a number, which is the total amount of reports on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getTWReportsCount
      security: []
  /twreport:
    get:
      tags:
        - Tube Worm Reports
      summary: Get a list of TW Reports
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getTWReports
      security: []
    post:
      tags:
        - Tube Worm Reports
      summary: Post a new TW Report
      description: To be used to submit new Reports to Canonn, note that the reportStatus should always be pending
      operationId: submitTWReport
      security: []
  /twreport/{id}:
    get:
      tags:
        - Tube Worm Reports
      summary: Get a Single TW Report
      description: Provide the ID to get a single report
      operationId: getTWReportById
      security: []
    put:
      tags:
        - Tube Worm Reports
      summary: Update a TW Report
      description: You do not need to send the entire report again, you can send only changed fields
      operationId: updateTWReportById
      security: []
    delete:
      tags:
        - Tube Worm Reports
      summary: Delete a TW Report
      description: The response is just an empty JSON, deleting a report requires auth
      operationId: removeTWReportById
      security:
        - canonnAuth: [reportDelete]
# TW Site
  /twsite/count:
    get:
      tags:
        - Tube Worms
      summary: Get a count of all TW Sites
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getTWSitesCount
      security: []
  /twsite:
    get:
      tags:
        - Tube Worms
      summary: Get a list of TW Sites
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getTWSites
      security: []
    post:
      tags:
        - Tube Worms
      summary: Post a new TW Site
      description: To be used to add a new site to the Canonn database, these are sites verified by Canonn
      operationId: submitTWSite
      security:
        - canonnAuth: [siteWrite]
  /twsite/{id}:
    get:
      tags:
        - Tube Worms
      summary: Get a Single TW Site
      description: Provide the ID to get a single site
      operationId: getTWSiteById
      security: []
    put:
      tags:
        - Tube Worms
      summary: Update a TW Site
      description: You do not need to send the entire site again, you can send only changed fields
      operationId: updateTWSiteById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Tube Worms
      summary: Delete a TW Site
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeTWSiteById
      security:
        - canonnAuth: [siteDelete]
# USS Report
  /ussreport/count:
    get:
      tags:
        - Unknown Signal Source Reports
      summary: Get a count of all USS Reports
      description: The API will respond with just a number, which is the total amount of reports on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getUSSReportsCount
      security: []
  /ussreport:
    get:
      tags:
        - Unknown Signal Source Reports
      summary: Get a list of USS Reports
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getUSSReports
      security: []
    post:
      tags:
        - Unknown Signal Source Reports
      summary: Post a new USS Report
      description: To be used to submit new Reports to Canonn, note that the reportStatus should always be pending
      operationId: submitUSSReport
      security: []
  /ussreport/{id}:
    get:
      tags:
        - Unknown Signal Source Reports
      summary: Get a Single USS Report
      description: Provide the ID to get a single report
      operationId: getUSSReportById
      security: []
    put:
      tags:
        - Unknown Signal Source Reports
      summary: Update a USS Report
      description: You do not need to send the entire report again, you can send only changed fields
      operationId: updateUSSReportById
      security: []
    delete:
      tags:
        - Unknown Signal Source Reports
      summary: Delete a USS Report
      description: The response is just an empty JSON, deleting a report requires auth
      operationId: removeUSSReportById
      security:
        - canonnAuth: [reportDelete]
# USS Site
  /usssite/count:
    get:
      tags:
        - Unknown Signal Sources
      summary: Get a count of all USS Sites
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getUSSSitesCount
      security: []
  /usssite:
    get:
      tags:
        - Unknown Signal Sources
      summary: Get a list of USS Sites
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getUSSSites
      security: []
    post:
      tags:
        - Unknown Signal Sources
      summary: Post a new USS Site
      description: To be used to add a new site to the Canonn database, these are sites verified by Canonn
      operationId: submitUSSSite
      security:
        - canonnAuth: [siteWrite]
  /usssite/{id}:
    get:
      tags:
        - Unknown Signal Sources
      summary: Get a Single USS Site
      description: Provide the ID to get a single site
      operationId: getUSSSiteById
      security: []
    put:
      tags:
        - Unknown Signal Sources
      summary: Update a USS Site
      description: You do not need to send the entire site again, you can send only changed fields
      operationId: updateUSSSiteById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Unknown Signal Sources
      summary: Delete a USS Site
      description: The response is just an empty JSON, deleting a site requires auth
      operationId: removeUSSSiteById
      security:
        - canonnAuth: [siteDelete]
# USS Type
  /usssitetype/count:
    get:
      tags:
        - Unknown Signal Sources
      summary: Get a count of all USS Site Types
      description: The API will respond with just a number, which is the total amount of sites on this endpoint. This can be used to filter, limit, or page other get requests.
      operationId: getUSSSiteTypesCount
      security: []
  /usssitetype:
    get:
      tags:
        - Unknown Signal Sources
      summary: Get a list of USS Site Types
      description: By default limited to the first 100 entries. Use filters, searching, or paging to get specific entries.
      operationId: getUSSSiteTypes
      security: []
    post:
      tags:
        - Unknown Signal Sources
      summary: Post a new USS Site Type
      description: To be used to add a new site type to the Canonn database
      operationId: submitUSSSiteType
      security:
        - canonnAuth: [siteWrite]
  /usssitetype/{id}:
    get:
      tags:
        - Unknown Signal Sources
      summary: Get a Single USS Site Type
      description: Provide the ID to get a single site
      operationId: getUSSSiteTypeById
      security: []
    put:
      tags:
        - Unknown Signal Sources
      summary: Update a USS Site Type
      description: The type should match those used by EDSM and in the Journal
      operationId: updateUSSSiteTypeById
      security:
        - canonnAuth: [siteWrite]
    delete:
      tags:
        - Unknown Signal Sources
      summary: Delete a USS Site Type
      description: The response is just an empty JSON, deleting a site type requires auth
      operationId: removeUSSSiteTypeById
      security:
        - canonnAuth: [siteDelete]
## Components
components:
  ## Responses
  ## Errors
    error400:
      description: You have made an error in your request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseError'
    error403:
      description: Forbidden, you are not logged in
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseError'
    error404:
      description: Count is Zero or Entry not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseError'
    error500:
      description: Server Error, please create an issue on Github
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/responseError'

  ## Path GET Parameters
  ## Security Schemes
  securitySchemes:

    userAuth:
      description: Canonn verification team authentication using JWT
      type: http
      scheme: bearer
      bearerFormat: jwt

    canonnAuth:
      description: Canonn admin team authentication using JWT
      type: http
      scheme: bearer
      bearerFormat: jwt

  ## Path Schemes
  ## Errors
    responseError:
      properties:
        statusCode:
          type: integer
        error:
          type: string
        message:
          type: string

  ## Authentication
    localCreds:
      required:
        - identifier
        - password
      properties:
        identifier:
          type: string
        password:
          type: string
          format: password

    authError:
      properties:
        statuscode:
          type: integer
        error:
          type: string
        message:
          type: string

    authLocal:
      properties:
        jwt:
          type: string
        user:
          $ref: '#/components/schemas/authUser'

    authUser:
      properties:
        username:
          type: string
        id:
          type: integer
        email:
          type: string
        provider:
          type: string
        role:
          $ref: '#/components/schemas/authRole'

    authRole:
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        type:
          type: string

  ## Global GET, POST, PUT Schemas

    bodySolidComposition:
      properties:
        ice:
          type: number
          format: float
        metal:
          type: number
          format: float
        rock:
          type: number
          format: float

    bodyAtmosphere:
      properties:
        argon:
          type: number
          format: float
        ammonia:
          type: number
          format: float
        carbonDioxide:
          type: number
          format: float
        hydrogen:
          type: number
          format: float
        helium:
          type: number
          format: float
        iron:
          type: number
          format: float
        neon:
          type: number
          format: float
        methane:
          type: number
          format: float
        nitrogen:
          type: number
          format: float
        oxygen:
          type: number
          format: float
        silicates:
          type: number
          format: float
        sulphurDioxide:
          type: number
          format: float
        water:
          type: number
          format: float

    bodyMaterial:
      properties:
        antimony:
          type: number
          format: float
        arsenic:
          type: number
          format: float
        boron:
          type: number
          format: float
        cadmium:
          type: number
          format: float
        carbon:
          type: number
          format: float
        chromium:
          type: number
          format: float
        germanium:
          type: number
          format: float
        iron:
          type: number
          format: float
        lead:
          type: number
          format: float
        manganese:
          type: number
          format: float
        mercury:
          type: number
          format: float
        molybdenum:
          type: number
          format: float
        nickel:
          type: number
          format: float
        niobium:
          type: number
          format: float
        phosphorus:
          type: number
          format: float
        polonium:
          type: number
          format: float
        rhenium:
          type: number
          format: float
        ruthenium:
          type: number
          format: float
        selenium:
          type: number
          format: float
        sulphur:
          type: number
          format: float
        technetium:
          type: number
          format: float
        tellurium:
          type: number
          format: float
        tin:
          type: number
          format: float
        tungsten:
          type: number
          format: float
        vanadium:
          type: number
          format: float
        yttrium:
          type: number
          format: float
        zinc:
          type: number
          format: float
        zirconium:
          type: number
          format: float

  ## GET Reports
    getReportPlanet:
      properties:
        id:
          type: integer
        systemName:
          type: string
        bodyName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        count:
          type: integer
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          $ref: '#/components/schemas/getSitePlanet'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getReportFM:
      properties:
        id:
          type: integer
        systemName:
          type: string
        bodyName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        count:
          type: integer
        type:
          type: string
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          $ref: '#/components/schemas/getSiteFM'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getReportGEN:
      properties:
        id:
          type: integer
        systemName:
          type: string
        orbitBody:
          type: string
        shipName:
          type: string
        directionSystem:
          type: string
        distance:
          type: number
          format: float
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          $ref: '#/components/schemas/getSiteGEN'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getReportGR:
      properties:
        id:
          type: integer
        systemName:
          type: string
        bodyName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        type:
          type: string
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          $ref: '#/components/schemas/getSiteGR'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getReportGRObeliskGroup:
      properties:
        id:
          type: integer
        grreport:
          type: integer
        grobeliskgroup:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getReportGRObelisk:
      properties:
        id:
          type: integer
        grreport:
          type: integer
        grobelisk:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getReportGS:
      properties:
        id:
          type: integer
        systemName:
          type: string
        bodyName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        type:
          type: string
        hasDatabank:
          type: boolean
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          $ref: '#/components/schemas/getSiteGS'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getReportGSObeliskGroup:
      properties:
        id:
          type: integer
        gsreport:
          type: integer
        gsobeliskgroup:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getReportGSObelisk:
      properties:
        id:
          type: integer
        gsreport:
          type: integer
        gsobelisk:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getReportGY:
      properties:
        id:
          type: integer
        systemName:
          type: string
        bodyName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        count:
          type: integer
        type:
          type: string
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          $ref: '#/components/schemas/getSiteGY'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getReportHD:
      properties:
        id:
          type: integer
        fromSystemName:
          type: string
        toSystemName:
          type: string
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
        reportComment:
          type: string
        added:
          type: boolean
        site:
          $ref: '#/components/schemas/getSiteHD'
        # Note this should have a ref to the breakdown of the json if possible
        hdRawJson:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getReportMS:
      properties:
        id:
          type: integer
        systemName:
          type: string
        orbitBody:
          type: string
        shipName:
          type: string
        shipTag:
          type: string
        type:
          type: string
        flightOps:
          type: boolean
        flightSchedule:
          type: boolean
        dockable:
          type: boolean
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          $ref: '#/components/schemas/getSiteMS'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getReportTB:
      properties:
        id:
          type: integer
        systemName:
          type: string
        bodyName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        type:
          type: string
        count:
          type: integer
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          $ref: '#/components/schemas/getSiteTB'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getReportTS:
      properties:
        id:
          type: integer
        systemName:
          type: string
        bodyName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        status:
          type: string
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          $ref: '#/components/schemas/getSiteTS'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getReportUSS:
      properties:
        id:
          type: integer
        systemName:
          type: string
        type:
          type: string
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
        reportComment:
          type: string
        added:
          type: boolean
        site:
          $ref: '#/components/schemas/getSiteUSS'
        # Note this should have a ref to the breakdown of the json if possible
        ussRawJson:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

  ## GET Locations
    getLocationSystem:
      properties:
        id:
          type: integer
        systemName:
          type: string
        edsmID:
          type: number
          format: float
        edsmID64:
          type: number
          format: double
        edsmCoordX:
          type: number
          format: double
        edsmCoordY:
          type: number
          format: double
        edsmCoordZ:
          type: number
          format: double
        edsmCoordLocked:
          type: boolean
        bodies:
          $ref: '#/components/schemas/getLocationBody'
        systemLocations:
          $ref: '#/components/schemas/getLocation'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getLocationBody:
      properties:
        id:
          type: integer
        system:
          $ref: '#/components/schemas/getLocationSystem'
        bodyName:
          type: string
        edsmID:
          type: number
          format: float
        edsmID64:
          type: number
          format: double
        edsmBodyID:
          type: integer
        edsmType:
          type: string
        edsmSubtype:
          type: string
        edsmOffset:
          type: integer
        edsmDistanceToArrival:
          type: number
          format: float
        edsmIsMainStar:
          type: boolean
        edsmIsScoopable:
          type: boolean
        edsmIsLandable:
          type: boolean
        edsmAge:
          type: integer
        edsmLuminosity:
          type: string
        edsmAbsoluteMagnitude:
          type: number
          format: float
        edsmSolarMasses:
          type: number
          format: float
        edsmSolarRadius:
          type: number
          format: float
        edsmGravity:
          type: number
          format: float
        edsmEarthMasses:
          type: number
          format: float
        edsmRadius:
          type: number
          format: float
        edsmSurfaceTemperature:
          type: number
          format: float
        edsmSurfacePressure:
          type: number
          format: float
        edsmVolcanismType:
          type: string
        edsmAtmosphereType:
          type: string
        edsmTerraformingState:
          type: string
        edsmOrbitalPeriod:
          type: number
          format: float
        edsmSemiMajorAxis:
          type: number
          format: float
        edsmOrbitalEccentricity:
          type: number
          format: float
        edsmOrbitalInclination:
          type: number
          format: float
        edsmArgOfPeriapsis:
          type: number
          format: float
        edsmRotationalPeriod:
          type: number
          format: float
        edsmRotationalPeriodTidallyLocked:
          type: boolean
        edsmAxialTilt:
          type: number
          format: float
        edsmSolidComposition:
          $ref: '#/components/schemas/bodySolidComposition'
        edsmAtmosphere:
          $ref: '#/components/schemas/bodyAtmosphere'
        edsmMaterial:
          $ref: '#/components/schemas/bodyMaterial'
        rings:
          $ref: '#/components/schemas/getLocationRing'
        bodyLocations:
          $ref: '#/components/schemas/getLocation'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getLocationRing:
      properties:
        id:
          type: integer
        body:
          $ref: '#/components/schemas/getLocationBody'
        ringName:
          type: string
        ringtype:
          $ref: '#/components/schemas/getLocationRingType'
        edsmMass:
          type: number
          format: float
        edsmInnerRadius:
          type: number
          format: float
        edsmOuterRadius:
          type: number
          format: float
        ringLocations:
          $ref: '#/components/schemas/getLocation'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getLocationRingType:
      properties:
        id:
          type: integer
        type:
          type: string

    getLocation:
      properties:
        id:
          type: integer
        system:
          type: integer
        body:
          type: integer
        ring:
          type: integer
        locationType:
          type: string
        bmSite:
          $ref: '#/components/schemas/getSitePlanet'
        btSite:
          $ref: '#/components/schemas/getSitePlanet'
        fgSite:
          $ref: '#/components/schemas/getSitePlanet'
        fmSite:
          $ref: '#/components/schemas/getSiteFM'
        genSite:
          $ref: '#/components/schemas/getSiteGEN'
        grSite:
          $ref: '#/components/schemas/getSiteGR'
        gsSite:
          $ref: '#/components/schemas/getSiteGR'
        gySite:
          $ref: '#/components/schemas/getSiteGY'
        hdSite:
          $ref: '#/components/schemas/getSiteHD'
        lsSite:
          $ref: '#/components/schemas/getSitePlanet'
        msSite:
          $ref: '#/components/schemas/getSiteMS'
        tbSite:
          $ref: '#/components/schemas/getSiteTB'
        tsSite:
          $ref: '#/components/schemas/getSiteTS'
        twSite:
          $ref: '#/components/schemas/getSitePlanet'
        ussSite:
          $ref: '#/components/schemas/getSiteUSS'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

  ## GET CMDRs
    getCMDR:
      properties:
        id:
          type: integer
        cmdrName:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getCMDRFactionKillReport:
      properties:
        id:
          type: integer
        systemName:
          type: string
        edTimestamp:
          type: string
          format: date-time
        cmdrName:
          type: string
        reward:
          type: integer
        rewardingFaction:
          type: string
        victimFaction:
          type: string
        # Note this needs to have a seperate schema with the breakdown of the event
        rawEvent:
          type: string
        isbeta:
          type: boolean

    getNHSSTopCMDRsByKill:
      properties:
        id:
          type: integer
        # Note this should instead be a oneWay relation to the CMDR Model
        cmdrName:
          type: string
        scoutKills:
          type: integer
        cyclopsKills:
          type: integer
        basiliskKills:
          type: integer
        medusaKills:
          type: integer
        unknownKills:
          type: integer
        scoutRewards:
          type: integer
        cyclopsRewards:
          type: integer
        basiliskRewards:
          type: integer
        medusaRewards:
          type: integer
        unknownRewards:
          type: integer
        totalRewards:
          type: integer
        totalKills:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

  ## GET Uploads

  ## GET JournalDumps
    getJournalData:
      properties:
        id:
          type: integer
        eventName:
          type: string
        systemName:
          type: string
        bodyName:
          type: string
        stationName:
          type: string
        cmdrName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        isBeta:
          type: boolean
        jsonData:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

  ## GET Sites
    getSitePlanet:
      properties:
        location:
          $ref: '#/components/schemas/getLocation'
        siteID:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        count:
          type: integer
        verified:
          type: boolean
        visible:
          type: boolean
        discoveredBy:
          $ref: '#/components/schemas/getCMDR'

    getSiteFM:
      properties:
        id:
          type: integer
        location:
          $ref: '#/components/schemas/getLocation'
        siteID:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        count:
          type: integer
        type:
          $ref: '#/components/schemas/getSiteFMType'
        verified:
          type: boolean
        visible:
          type: boolean
        discoveredBy:
          $ref: '#/components/schemas/getCMDR'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getSiteFMType:
      properties:
        id:
          type: integer
        type:
          type: string

    getSiteGEN:
      properties:
        id:
          type: integer
        location:
          $ref: '#/components/schemas/getLocation'
        siteID:
          type: integer
        shipName:
          type: string
        directionSystem:
          $ref: '#/components/schemas/getLocationSystem'
        distance:
          type: number
          format: float
        discoveredBy:
          $ref: '#/components/schemas/getCMDR'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getSiteGR:
      properties:
        id:
          type: integer
        location:
          $ref: '#/components/schemas/getLocation'
        siteID:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        type:
          $ref: '#/components/schemas/getSiteGRType'
        verified:
          type: boolean
        visible:
          type: boolean
        discoveredBy:
          $ref: '#/components/schemas/getCMDR'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getSiteGRType:
      properties:
        id:
          type: integer
        type:
          type: string

    getSiteGRActiveGroup:
      properties:
        grSite:
          $ref: '#/components/schemas/getSiteGR'
        activeGroup:
          $ref: '#/components/schemas/getSiteGRObeliskGroup'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getSiteGRActiveObelisk:
      properties:
        id:
          type: integer
        grSite:
          $ref: '#/components/schemas/getSiteGR'
        activeObelisk:
          $ref: '#/components/schemas/getSiteGRObelisk'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getSiteGRArtifact:
      properties:
        id:
          type: integer
        artifactName:
          type: string

    getSiteGRCodexCategory:
      properties:
        id:
          type: integer
        categoryName:
          type: string

    getSiteGRCodexData:
      properties:
        id:
          type: integer
        grCodexCategory:
          $ref: '#/components/schemas/getSiteGRCodexCategory'
        grPrimaryArtifact:
          $ref: '#/components/schemas/getSiteGRArtifact'
        grSecondaryArtifact:
          $ref: '#/components/schemas/getSiteGRArtifact'
        codexNumber:
          type: integer
        text:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getSiteGRObelisk:
      properties:
        id:
          type: integer
        grType:
          $ref: '#/components/schemas/getSiteGRType'
        grObeliskGroup:
          $ref: '#/components/schemas/getSiteGRObeliskGroup'
        obeliskNumber:
          type: integer
        broken:
          type: boolean
        grCodexData:
          $ref: '#/components/schemas/getSiteGRCodexData'
        verified:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getSiteGRObeliskGroup:
      properties:
        id:
          type: integer
        grType:
          $ref: '#/components/schemas/getSiteGRType'
        groupName:
          type: string
        amount:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getSiteGS:
      properties:
        id:
          type: integer
        location:
          $ref: '#/components/schemas/getLocation'
        siteID:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        type:
          $ref: '#/components/schemas/getSiteGSType'
        hasDatabank:
          type: boolean
        verified:
          type: boolean
        visible:
          type: boolean
        discoveredBy:
          $ref: '#/components/schemas/getCMDR'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getSiteGSType:
      properties:
        id:
          type: integer
        type:
          type: string
        journalName:
          type: string

    getSiteGSActiveGroup:
      properties:
        id:
          type: integer
        gsSite:
          $ref: '#/components/schemas/getSiteGS'
        activeGroup:
          $ref: '#/components/schemas/getSiteGSObeliskGroup'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getSiteGSActiveObelisk:
      properties:
        id:
          type: integer
        gsSite:
          $ref: '#/components/schemas/getSiteGS'
        activeObelisk:
          $ref: '#/components/schemas/getSiteGSObelisk'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getSiteGSArtifact:
      properties:
        id:
          type: integer
        artifactName:
          type: string

    getSiteGSCodexCategory:
      properties:
        id:
          type: integer
        categoryName:
          type: string

    getSiteGSCodexData:
      properties:
        id:
          type: integer
        gsCodexCategory:
          $ref: '#/components/schemas/getSiteGSCodexCategory'
        gsPrimaryArtifact:
          $ref: '#/components/schemas/getSiteGSArtifact'
        gsSecondaryArtifact:
          $ref: '#/components/schemas/getSiteGSArtifact'
        codexNumber:
          type: integer
        text:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getSiteGSObelisk:
      properties:
        id:
          type: integer
        gsType:
          $ref: '#/components/schemas/getSiteGSType'
        gsObeliskGroup:
          $ref: '#/components/schemas/getSiteGSObeliskGroup'
        obeliskNumber:
          type: integer
        broken:
          type: boolean
        gsCodexData:
          $ref: '#/components/schemas/getSiteGSCodexData'
        verified:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getSiteGSObeliskGroup:
      properties:
        id:
          type: integer
        gsType:
          $ref: '#/components/schemas/getSiteGSType'
        gsoupName:
          type: string
        amount:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getSiteGY:
      properties:
        id:
          type: integer
        location:
          $ref: '#/components/schemas/getLocation'
        siteID:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        count:
          type: integer
        type:
          $ref: '#/components/schemas/getSiteGYType'
        verified:
          type: boolean
        visible:
          type: boolean
        discoveredBy:
          $ref: '#/components/schemas/getCMDR'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getSiteGYType:
      properties:
        id:
          type: integer
        type:
          type: string

    getSiteHD:
      properties:
        id:
          type: integer
        location:
          $ref: '#/components/schemas/getLocation'
        toSystem:
          $ref: '#/components/schemas/getLocationSystem'
        thargoidCount:
          type: integer
        isHostile:
          type: boolean
        discoveredBy:
          $ref: '#/components/schemas/getCMDR'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getSiteMS:
      properties:
        id:
          type: integer
        location:
          $ref: '#/components/schemas/getLocation'
        siteID:
          type: integer
        shipName:
          type: string
        shipTag:
          type: string
        type:
          $ref: '#/components/schemas/getSiteMSType'
        flightOps:
          type: boolean
        flightSchedule:
          type: boolean
        dockable:
          type: boolean
        discoveredBy:
          $ref: '#/components/schemas/getCMDR'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getSiteMSType:
      properties:
        id:
          type: integer
        type:
          type: string

    getSiteTB:
      properties:
        id:
          type: integer
        location:
          $ref: '#/components/schemas/getLocation'
        siteID:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        type:
          $ref: '#/components/schemas/getSiteTBType'
        verified:
          type: boolean
        visible:
          type: boolean
        discoveredBy:
          $ref: '#/components/schemas/getCMDR'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getSiteTBType:
      properties:
        id:
          type: integer
        type:
          type: string

    getSiteTS:
      properties:
        id:
          type: integer
        location:
          $ref: '#/components/schemas/getLocation'
        siteID:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        status:
          $ref: '#/components/schemas/getSiteTSStatus'
        verified:
          type: boolean
        visible:
          type: boolean
        discoveredBy:
          $ref: '#/components/schemas/getCMDR'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getSiteTSStatus:
      properties:
        id:
          type: integer
        type:
          type: string

    getSiteUSS:
      properties:
        id:
          type: integer
        location:
          $ref: '#/components/schemas/getLocation'
        type:
          $ref: '#/components/schemas/getSiteUSSType'
        threatLevel:
          type: integer
        discoveredBy:
          $ref: '#/components/schemas/getCMDR'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    getSiteUSSType:
      properties:
        id:
          type: integer
        type:
          type: string
        journalName:
          type: string

  ## POST Reports
    postReportPlanet:
      required:
        - systemName
        - bodyName
        - latitude
        - longitude
        - cmdrName
        - reportStatus
      properties:
        systemName:
          type: string
        bodyName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        count:
          type: integer
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
          enum:
            - pending
            - updated
            - accepted
            - declined
            - issue
          default: pending
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          type: integer

    postReportPlanetWithType:
      required:
        - systemName
        - bodyName
        - latitude
        - longitude
        - type
        - cmdrName
        - reportStatus
      properties:
        systemName:
          type: string
        bodyName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        count:
          type: integer
        type:
          type: string
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
          enum:
            - pending
            - updated
            - accepted
            - declined
            - issue
          default: pending
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          type: integer

    postReportGEN:
      required:
        - systemName
        - shipName
        - cmdrName
        - reportStatus
      properties:
        systemName:
          type: string
        orbitBody:
          type: string
        shipName:
          type: string
        directionSystem:
          type: string
        distance:
          type: number
          format: float
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
          enum:
            - pending
            - updated
            - accepted
            - declined
            - issue
          default: pending
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          type: integer

    postReportGR:
      required:
        - systemName
        - bodyName
        - latitude
        - longitude
        - type
        - cmdrName
        - reportStatus
      properties:
        systemName:
          type: string
        bodyName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        type:
          type: string
          enum:
            - Alpha
            - Beta
            - Gamma
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
          enum:
            - pending
            - updated
            - accepted
            - declined
            - issue
          default: pending
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          type: integer

    postReportGRObeliskGroup:
      required:
        - grreport
        - grobeliskgroup
      properties:
        grreport:
          type: integer
        grobeliskgroup:
          type: integer

    postReportGRObelisk:
      required:
        - grreport
        - grobelisk
      properties:
        grreport:
          type: integer
        grobelisk:
          type: integer

    postReportGS:
      required:
        - systemName
        - bodyName
        - latitude
        - longitude
        - type
        - hasDatabank
        - cmdrName
        - reportStatus
      properties:
        systemName:
          type: string
        bodyName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        type:
          type: string
          enum:
            - Lacrosse
            - Crossroads
            - Fistbump
            - Hammerbot
            - Bear
            - Bowl
            - Turtle
        hasDatabank:
          type: boolean
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
          enum:
            - pending
            - updated
            - accepted
            - declined
            - issue
          default: pending
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          type: integer

    postReportGSObeliskGroup:
      required:
        - gsreport
        - gsobeliskgroup
      properties:
        gsreport:
          type: integer
        gsobeliskgroup:
          type: integer

    postReportGSObelisk:
      required:
        - gsreport
        - gsobelisk
      properties:
        gsreport:
          type: integer
        gsobelisk:
          type: integer

    postReportHD:
      required:
        - fromSystemName
        - toSystemName
        - cmdrName
        - reportStatus
        - hdRawJson
      properties:
        fromSystemName:
          type: string
        toSystemName:
          type: string
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
          enum:
            - pending
            - updated
            - accepted
            - declined
            - issue
          default: pending
        reportComment:
          type: string
        added:
          type: boolean
        site:
          type: integer
        hdRawJson:
          type: string

    postReportMS:
      required:
        - systemName
        - shipName
        - type
        - flightOps
        - flightSchedule
        - dockable
        - cmdrName
        - reportStatus
      properties:
        systemName:
          type: string
        orbitBody:
          type: string
        shipName:
          type: string
        shipTag:
          type: string
        type:
          type: string
        flightOps:
          type: boolean
        flightSchedule:
          type: boolean
        dockable:
          type: boolean
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
          enum:
            - pending
            - updated
            - accepted
            - declined
            - issue
          default: pending
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          type: integer

    postReportTB:
      required:
        - systemName
        - bodyName
        - latitude
        - longitude
        - type
        - cmdrName
        - reportStatus
      properties:
        systemName:
          type: string
        bodyName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        type:
          type: string
          enum:
            - Barnacle
            - Megabarnacle
        count:
          type: integer
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
          enum:
            - pending
            - updated
            - accepted
            - declined
            - issue
          default: pending
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          type: integer

    postReportTS:
      required:
        - systemName
        - bodyName
        - latitude
        - longitude
        - status
        - cmdrName
        - reportStatus
      properties:
        systemName:
          type: string
        bodyName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        status:
          type: string
          enum:
            - Active
            - Inactive
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
          enum:
            - pending
            - updated
            - accepted
            - declined
            - issue
          default: pending
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          type: integer

    postReportUSS:
      required:
        - systemName
        - cmdrName
        - reportStatus
        - ussRawJson
      properties:
        systemName:
          type: string
        type:
          type: string
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
          enum:
            - pending
            - updated
            - accepted
            - declined
            - issue
          default: pending
        reportComment:
          type: string
        added:
          type: boolean
        site:
          type: integer
        ussRawJson:
          type: string

  ## POST Locations
    postLocationSystem:
      required:
        - systemName
      properties:
        systemName:
          type: string
        edsmID:
          type: number
          format: float
        edsmID64:
          type: number
          format: double
        edsmCoordX:
          type: number
          format: double
        edsmCoordY:
          type: number
          format: double
        edsmCoordZ:
          type: number
          format: double
        edsmCoordLocked:
          type: boolean

    postLocationBody:
      required:
        - bodyName
      properties:
        system:
          type: integer
        bodyName:
          type: string
        edsmID:
          type: number
          format: float
        edsmID64:
          type: number
          format: double
        edsmBodyID:
          type: integer
        edsmType:
          type: string
        edsmSubtype:
          type: string
        edsmOffset:
          type: integer
        edsmDistanceToArrival:
          type: number
          format: float
        edsmIsMainStar:
          type: boolean
        edsmIsScoopable:
          type: boolean
        edsmIsLandable:
          type: boolean
        edsmAge:
          type: integer
        edsmLuminosity:
          type: string
        edsmAbsoluteMagnitude:
          type: number
          format: float
        edsmSolarMasses:
          type: number
          format: float
        edsmSolarRadius:
          type: number
          format: float
        edsmGravity:
          type: number
          format: float
        edsmEarthMasses:
          type: number
          format: float
        edsmRadius:
          type: number
          format: float
        edsmSurfaceTemperature:
          type: number
          format: float
        edsmSurfacePressure:
          type: number
          format: float
        edsmVolcanismType:
          type: string
        edsmAtmosphereType:
          type: string
        edsmTerraformingState:
          type: string
        edsmOrbitalPeriod:
          type: number
          format: float
        edsmSemiMajorAxis:
          type: number
          format: float
        edsmOrbitalEccentricity:
          type: number
          format: float
        edsmOrbitalInclination:
          type: number
          format: float
        edsmArgOfPeriapsis:
          type: number
          format: float
        edsmRotationalPeriod:
          type: number
          format: float
        edsmRotationalPeriodTidallyLocked:
          type: boolean
        edsmAxialTilt:
          type: number
          format: float
        edsmSolidComposition:
          $ref: '#/components/schemas/bodySolidComposition'
        edsmAtmosphere:
          $ref: '#/components/schemas/bodyAtmosphere'
        edsmMaterial:
          $ref: '#/components/schemas/bodyMaterial'

    postLocationRing:
      required:
        - body
        - ringName
      properties:
        body:
          type: integer
        ringName:
          type: string
        ringtype:
          type: integer
        edsmMass:
          type: number
          format: float
        edsmInnerRadius:
          type: number
          format: float
        edsmOuterRadius:
          type: number
          format: float

    postLocationRingType:
      required:
        - type
      properties:
        type:
          type: string

    postLocation:
      required:
        - system
        - locationType
      properties:
        system:
          type: integer
        body:
          type: integer
        ring:
          type: integer
        locationType:
          type: string
          enum:
            - BM
            - BT
            - FG
            - FM
            - GEN
            - GR
            - GS
            - GY
            - HD
            - LS
            - MS
            - TB
            - TS
            - TW
            - USS

  ## POST CMDRs
    postCMDR:
      required:
        - cmdrName
      properties:
        cmdrName:
          type: string

    postCMDRFactionKillReport:
      required:
        - systemName
        - cmdrName
      properties:
        systemName:
          type: string
        edTimestamp:
          type: string
          format: date-time
        cmdrName:
          type: string
        reward:
          type: integer
        rewardingFaction:
          type: string
        victimFaction:
          type: string
        # Note this needs to have a seperate schema with the breakdown of the event
        rawEvent:
          type: string
        isbeta:
          type: boolean

    postNHSSTopCMDRsByKill:
      required:
        - cmdrName
      properties:
        cmdrName:
          type: string
        scoutKills:
          type: integer
        cyclopsKills:
          type: integer
        basiliskKills:
          type: integer
        medusaKills:
          type: integer
        unknownKills:
          type: integer
        scoutRewards:
          type: integer
        cyclopsRewards:
          type: integer
        basiliskRewards:
          type: integer
        medusaRewards:
          type: integer
        unknownRewards:
          type: integer
        totalRewards:
          type: integer
        totalKills:
          type: integer

  ## POST Uploads

  ## POST JournalDumps
    postJournalData:
      required:
        - jsonData
      properties:
        eventName:
          type: string
        systemName:
          type: string
        bodyName:
          type: string
        stationName:
          type: string
        cmdrName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        isBeta:
          type: boolean
        jsonData:
          type: string

  ## POST Sites
    postSitePlanet:
      required:
        - locationType
        - siteID
        - latitude
        - longitude
        - verified
        - discoveredBy
      properties:
        location:
          type: integer
        siteID:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        count:
          type: integer
        verified:
          type: boolean
        visible:
          type: boolean
        discoveredBy:
          type: integer

    postSiteFM:
      required:
        - location
        - siteID
        - latitude
        - longitude
        - type
        - verified
        - discoveredBy
      properties:
        location:
          type: integer
        siteID:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        count:
          type: integer
        type:
          type: integer
        verified:
          type: boolean
        visible:
          type: boolean
        discoveredBy:
          type: integer

    postSiteFMType:
      required:
        - type
      properties:
        type:
          type: string

    postSiteGEN:
      required:
        - location
        - siteID
        - shipName
        - discoveredBy
      properties:
        location:
          type: integer
        siteID:
          type: integer
        shipName:
          type: string
        directionSystem:
          type: integer
        distance:
          type: number
          format: float
        discoveredBy:
          type: integer

    postSiteGR:
      required:
        - location
        - siteID
        - latitude
        - longitude
        - type
        - verified
        - discoveredBy
      properties:
        location:
          type: integer
        siteID:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        type:
          type: integer
        verified:
          type: boolean
        visible:
          type: boolean
        discoveredBy:
          type: integer

    postSiteGRType:
      required:
        - type
      properties:
        type:
          type: string

    postSiteGRActiveGroup:
      required:
        - grSite
        - activeGroup
      properties:
        grSite:
          type: integer
        activeGroup:
          type: integer

    postSiteGRActiveObelisk:
      required:
        - grSite
        - activeObelisk
      properties:
        grSite:
          type: integer
        activeObelisk:
          type: integer

    postSiteGRArtifact:
      required:
        - artifactName
      properties:
        artifactName:
          type: string

    postSiteGRCodexCategory:
      required:
        - categoryName
      properties:
        categoryName:
          type: string

    postSiteGRCodexData:
      required:
        - grCodexCategory
        - grPrimaryArtifact
        - grSecondaryArtifact
        - codexNumber
        - text
      properties:
        grCodexCategory:
          type: integer
        grPrimaryArtifact:
          type: integer
        grSecondaryArtifact:
          type: integer
        codexNumber:
          type: integer
        text:
          type: string

    postSiteGRObelisk:
      required:
        - grType
        - grObeliskGroup
        - obeliskNumber
        - broken
        - grCodexData
        - verified
      properties:
        grType:
          type: integer
        grObeliskGroup:
          type: string
        obeliskNumber:
          type: integer
        broken:
          type: boolean
        grCodexData:
          type: integer
        verified:
          type: boolean

    postSiteGRObeliskGroup:
      required:
        - grType
        - groupName
        - amount
      properties:
        grType:
          type: integer
        groupName:
          type: string
        amount:
          type: integer

    postSiteGS:
      required:
        - location
        - siteID
        - latitude
        - longitude
        - type
        - hasDatabank
        - verified
        - discoveredBy
      properties:
        location:
          type: integer
        siteID:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        type:
          type: integer
        hasDatabank:
          type: boolean
        verified:
          type: boolean
        visible:
          type: boolean
        discoveredBy:
          type: integer

    postSiteGSType:
      required:
        - type
        - journalName
      properties:
        type:
          type: string
        journalName:
          type: string

    postSiteGSActiveGroup:
      required:
        - gsSite
        - activeGroup
      properties:
        gsSite:
          type: integer
        activeGroup:
          type: integer

    postSiteGSActiveObelisk:
      required:
        - gsSite
        - activeObelisk
      properties:
        gsSite:
          type: integer
        activeObelisk:
          type: integer

    postSiteGSArtifact:
      required:
        - artifactName
      properties:
        artifactName:
          type: string

    postSiteGSCodexCategory:
      required:
        - categoryName
      properties:
        categoryName:
          type: string

    postSiteGSCodexData:
      required:
        - gsCodexCategory
        - gsPrimaryArtifact
        - gsSecondaryArtifact
        - codexNumber
        - text
      properties:
        gsCodexCategory:
          type: integer
        gsPrimaryArtifact:
          type: integer
        gsSecondaryArtifact:
          type: integer
        codexNumber:
          type: integer
        text:
          type: string

    postSiteGSObelisk:
      required:
        - gsType
        - gsObeliskGroup
        - obeliskNumber
        - broken
        - gsCodexData
        - verified
      properties:
        gsType:
          type: integer
        gsObeliskGroup:
          type: string
        obeliskNumber:
          type: integer
        broken:
          type: boolean
        gsCodexData:
          type: integer
        verified:
          type: boolean

    postSiteGSObeliskGroup:
      required:
        - gsType
        - gsoupName
        - amount
      properties:
        gsType:
          type: integer
        gsoupName:
          type: string
        amount:
          type: integer

    postSiteGY:
      required:
        - location
        - siteID
        - latitude
        - longitude
        - type
        - verified
        - discoveredBy
      properties:
        location:
          type: integer
        siteID:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        count:
          type: integer
        type:
          type: integer
        verified:
          type: boolean
        visible:
          type: boolean
        discoveredBy:
          type: integer

    postSiteGYType:
      required:
        - type
      properties:
        type:
          type: string

    postSiteHD:
      required:
        - location
        - toSystem
        - thargoidCount
        - isHostile
        - discoveredBy
      properties:
        location:
          type: integer
        toSystem:
          type: integer
        thargoidCount:
          type: integer
        isHostile:
          type: boolean
        discoveredBy:
          type: integer

    postSiteMS:
      required:
        - location
        - siteID
        - shipName
        - shipTag
        - type
        - flightOps
        - flightSchedule
        - dockable
        - discoveredBy
      properties:
        location:
          type: integer
        siteID:
          type: integer
        shipName:
          type: string
        shipTag:
          type: string
        type:
          type: integer
        flightOps:
          type: boolean
        flightSchedule:
          type: boolean
        dockable:
          type: boolean
        discoveredBy:
          type: integer

    postSiteMSType:
      required:
        - type
      properties:
        type:
          type: string

    postSiteTB:
      required:
        - location
        - siteID
        - latitude
        - longitude
        - type
        - verified
        - discoveredBy
      properties:
        location:
          type: integer
        siteID:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        type:
          type: integer
        verified:
          type: boolean
        visible:
          type: boolean
        discoveredBy:
          type: integer

    postSiteTBType:
      required:
        - type
      properties:
        type:
          type: string

    postSiteTS:
      required:
        - location
        - siteID
        - latitude
        - longitude
        - type
        - verified
        - discoveredBy
      properties:
        location:
          type: integer
        siteID:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        status:
          type: integer
        verified:
          type: boolean
        visible:
          type: boolean
        discoveredBy:
          type: integer

    postSiteTSStatus:
      required:
        - status
      properties:
        type:
          type: string

    postSiteUSS:
      required:
        - location
        - type
        - threatLevel
        - discoveredBy
      properties:
        location:
          type: integer
        type:
          type: integer
        threatLevel:
          type: integer
        discoveredBy:
          type: integer

    postSiteUSSType:
      required:
        - type
        - journalName
      properties:
        type:
          type: string
        journalName:
          type: string

  ## PUT Reports
    putReportPlanet:
      properties:
        systemName:
          type: string
        bodyName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        count:
          type: integer
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
          enum:
            - pending
            - updated
            - accepted
            - declined
            - issue
          default: pending
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          type: integer

    putReportPlanetWithType:
      properties:
        systemName:
          type: string
        bodyName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        count:
          type: integer
        type:
          type: string
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
          enum:
            - pending
            - updated
            - accepted
            - declined
            - issue
          default: pending
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          type: integer

    putReportGEN:
      properties:
        systemName:
          type: string
        orbitBody:
          type: string
        shipName:
          type: string
        directionSystem:
          type: string
        distance:
          type: number
          format: float
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
          enum:
            - pending
            - updated
            - accepted
            - declined
            - issue
          default: pending
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          type: integer

    putReportGR:
      properties:
        systemName:
          type: string
        bodyName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        type:
          type: string
          enum:
            - Alpha
            - Beta
            - Gamma
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
          enum:
            - pending
            - updated
            - accepted
            - declined
            - issue
          default: pending
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          type: integer

    putReportGRObeliskGroup:
      properties:
        grreport:
          type: integer
        grobeliskgroup:
          type: integer

    putReportGRObelisk:
      properties:
        grreport:
          type: integer
        grobelisk:
          type: integer

    putReportGS:
      properties:
        systemName:
          type: string
        bodyName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        type:
          type: string
          enum:
            - Lacrosse
            - Crossroads
            - Fistbump
            - Hammerbot
            - Bear
            - Bowl
            - Turtle
        hasDatabank:
          type: boolean
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
          enum:
            - pending
            - updated
            - accepted
            - declined
            - issue
          default: pending
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          type: integer

    putReportGSObeliskGroup:
      properties:
        gsreport:
          type: integer
        gsobeliskgroup:
          type: integer

    putReportGSObelisk:
      properties:
        gsreport:
          type: integer
        gsobelisk:
          type: integer

    putReportHD:
      properties:
        fromSystemName:
          type: string
        toSystemName:
          type: string
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
          enum:
            - pending
            - updated
            - accepted
            - declined
            - issue
          default: pending
        reportComment:
          type: string
        added:
          type: boolean
        site:
          type: integer
        hdRawJson:
          type: string

    putReportMS:
      properties:
        systemName:
          type: string
        orbitBody:
          type: string
        shipName:
          type: string
        shipTag:
          type: string
        type:
          type: string
        flightOps:
          type: boolean
        flightSchedule:
          type: boolean
        dockable:
          type: boolean
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
          enum:
            - pending
            - updated
            - accepted
            - declined
            - issue
          default: pending
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          type: integer

    putReportTB:
      properties:
        systemName:
          type: string
        bodyName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        type:
          type: string
          enum:
            - Barnacle
            - Megabarnacle
        count:
          type: integer
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
          enum:
            - pending
            - updated
            - accepted
            - declined
            - issue
          default: pending
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          type: integer

    putReportTS:
      properties:
        systemName:
          type: string
        bodyName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        status:
          type: string
          enum:
            - Active
            - Inactive
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
          enum:
            - pending
            - updated
            - accepted
            - declined
            - issue
          default: pending
        reportComment:
          type: string
        voteCount:
          type: integer
        added:
          type: boolean
        site:
          type: integer

    putReportUSS:
      properties:
        systemName:
          type: string
        type:
          type: string
        cmdrName:
          type: string
        cmdrComment:
          type: string
        isBeta:
          type: boolean
        reportStatus:
          type: string
          enum:
            - pending
            - updated
            - accepted
            - declined
            - issue
          default: pending
        reportComment:
          type: string
        added:
          type: boolean
        site:
          type: integer
        ussRawJson:
          type: string

  ## PUT Locations
    putLocationSystem:
      properties:
        systemName:
          type: string
        edsmID:
          type: number
          format: float
        edsmID64:
          type: number
          format: double
        edsmCoordX:
          type: number
          format: double
        edsmCoordY:
          type: number
          format: double
        edsmCoordZ:
          type: number
          format: double
        edsmCoordLocked:
          type: boolean

    putLocationBody:
      properties:
        system:
          type: integer
        bodyName:
          type: string
        edsmID:
          type: number
          format: float
        edsmID64:
          type: number
          format: double
        edsmBodyID:
          type: integer
        edsmType:
          type: string
        edsmSubtype:
          type: string
        edsmOffset:
          type: integer
        edsmDistanceToArrival:
          type: number
          format: float
        edsmIsMainStar:
          type: boolean
        edsmIsScoopable:
          type: boolean
        edsmIsLandable:
          type: boolean
        edsmAge:
          type: integer
        edsmLuminosity:
          type: string
        edsmAbsoluteMagnitude:
          type: number
          format: float
        edsmSolarMasses:
          type: number
          format: float
        edsmSolarRadius:
          type: number
          format: float
        edsmGravity:
          type: number
          format: float
        edsmEarthMasses:
          type: number
          format: float
        edsmRadius:
          type: number
          format: float
        edsmSurfaceTemperature:
          type: number
          format: float
        edsmSurfacePressure:
          type: number
          format: float
        edsmVolcanismType:
          type: string
        edsmAtmosphereType:
          type: string
        edsmTerraformingState:
          type: string
        edsmOrbitalPeriod:
          type: number
          format: float
        edsmSemiMajorAxis:
          type: number
          format: float
        edsmOrbitalEccentricity:
          type: number
          format: float
        edsmOrbitalInclination:
          type: number
          format: float
        edsmArgOfPeriapsis:
          type: number
          format: float
        edsmRotationalPeriod:
          type: number
          format: float
        edsmRotationalPeriodTidallyLocked:
          type: boolean
        edsmAxialTilt:
          type: number
          format: float
        edsmSolidComposition:
          $ref: '#/components/schemas/bodySolidComposition'
        edsmAtmosphere:
          $ref: '#/components/schemas/bodyAtmosphere'
        edsmMaterial:
          $ref: '#/components/schemas/bodyMaterial'

    putLocationRing:
      properties:
        body:
          type: integer
        ringName:
          type: string
        ringtype:
          type: integer
        edsmMass:
          type: number
          format: float
        edsmInnerRadius:
          type: number
          format: float
        edsmOuterRadius:
          type: number
          format: float

    putLocationRingType:
      properties:
        type:
          type: string

    putLocation:
      properties:
        system:
          type: integer
        body:
          type: integer
        ring:
          type: integer
        locationType:
          type: string
          enum:
            - BM
            - BT
            - FG
            - FM
            - GEN
            - GR
            - GS
            - GY
            - HD
            - LS
            - MS
            - TB
            - TS
            - TW
            - USS

  ## PUT CMDRs
    putCMDR:
      properties:
        cmdrName:
          type: string

    putCMDRFactionKillReport:
      properties:
        systemName:
          type: string
        edTimestamp:
          type: string
          format: date-time
        cmdrName:
          type: string
        reward:
          type: integer
        rewardingFaction:
          type: string
        victimFaction:
          type: string
        rawEvent:
          type: string
        isbeta:
          type: boolean

    putNHSSTopCMDRsByKill:
      properties:
        cmdrName:
          type: string
        scoutKills:
          type: integer
        cyclopsKills:
          type: integer
        basiliskKills:
          type: integer
        medusaKills:
          type: integer
        unknownKills:
          type: integer
        scoutRewards:
          type: integer
        cyclopsRewards:
          type: integer
        basiliskRewards:
          type: integer
        medusaRewards:
          type: integer
        unknownRewards:
          type: integer
        totalRewards:
          type: integer
        totalKills:
          type: integer

  ## PUT Uploads

  ## PUT JournalDumps
    putJournalData:
      properties:
        eventName:
          type: string
        systemName:
          type: string
        bodyName:
          type: string
        stationName:
          type: string
        cmdrName:
          type: string
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        isBeta:
          type: boolean
        jsonData:
          type: string

  ## PUT Sites
    putSitePlanet:
      properties:
        location:
          type: integer
        siteID:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        count:
          type: integer
        verified:
          type: boolean
        visible:
          type: boolean
        discoveredBy:
          type: integer

    putSiteFM:
      properties:
        location:
          type: integer
        siteID:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        count:
          type: integer
        type:
          type: integer
        verified:
          type: boolean
        visible:
          type: boolean
        discoveredBy:
          type: integer

    putSiteFMType:
      properties:
        type:
          type: string

    putSiteGEN:
      properties:
        location:
          type: integer
        siteID:
          type: integer
        shipName:
          type: string
        directionSystem:
          type: integer
        distance:
          type: number
          format: float
        discoveredBy:
          type: integer

    putSiteGR:
      properties:
        location:
          type: integer
        siteID:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        type:
          type: integer
        verified:
          type: boolean
        visible:
          type: boolean
        discoveredBy:
          type: integer

    putSiteGRType:
      properties:
        type:
          type: string

    putSiteGRActiveGroup:
      properties:
        grSite:
          type: integer
        activeGroup:
          type: integer

    putSiteGRActiveObelisk:
      properties:
        grSite:
          type: integer
        activeObelisk:
          type: integer

    putSiteGRArtifact:
      properties:
        artifactName:
          type: string

    putSiteGRCodexCategory:
      properties:
        categoryName:
          type: string

    putSiteGRCodexData:
      properties:
        grCodexCategory:
          type: integer
        grPrimaryArtifact:
          type: integer
        grSecondaryArtifact:
          type: integer
        codexNumber:
          type: integer
        text:
          type: string

    putSiteGRObelisk:
      properties:
        grType:
          type: integer
        grObeliskGroup:
          type: string
        obeliskNumber:
          type: integer
        broken:
          type: boolean
        grCodexData:
          type: integer
        verified:
          type: boolean

    putSiteGRObeliskGroup:
      properties:
        grType:
          type: integer
        groupName:
          type: string
        amount:
          type: integer

    putSiteGS:
      properties:
        location:
          type: integer
        siteID:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        type:
          type: integer
        hasDatabank:
          type: boolean
        verified:
          type: boolean
        visible:
          type: boolean
        discoveredBy:
          type: integer

    putSiteGSType:
      properties:
        type:
          type: string
        journalName:
          type: string

    putSiteGSActiveGroup:
      properties:
        gsSite:
          type: integer
        activeGroup:
          type: integer

    putSiteGSActiveObelisk:
      properties:
        gsSite:
          type: integer
        activeObelisk:
          type: integer

    putSiteGSArtifact:
      properties:
        artifactName:
          type: string

    putSiteGSCodexCategory:
      properties:
        categoryName:
          type: string

    putSiteGSCodexData:
      properties:
        gsCodexCategory:
          type: integer
        gsPrimaryArtifact:
          type: integer
        gsSecondaryArtifact:
          type: integer
        codexNumber:
          type: integer
        text:
          type: string

    putSiteGSObelisk:
      properties:
        gsType:
          type: integer
        gsObeliskGroup:
          type: string
        obeliskNumber:
          type: integer
        broken:
          type: boolean
        gsCodexData:
          type: integer
        verified:
          type: boolean

    putSiteGSObeliskGroup:
      properties:
        gsType:
          type: integer
        gsoupName:
          type: string
        amount:
          type: integer

    putSiteGY:
      properties:
        location:
          type: integer
        siteID:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        count:
          type: integer
        type:
          type: integer
        verified:
          type: boolean
        visible:
          type: boolean
        discoveredBy:
          type: integer

    putSiteGYType:
      properties:
        type:
          type: string

    putSiteHD:
      properties:
        location:
          type: integer
        toSystem:
          type: integer
        thargoidCount:
          type: integer
        isHostile:
          type: boolean
        discoveredBy:
          type: integer

    putSiteMS:
      properties:
        location:
          type: integer
        siteID:
          type: integer
        shipName:
          type: string
        shipTag:
          type: string
        type:
          type: integer
        flightOps:
          type: boolean
        flightSchedule:
          type: boolean
        dockable:
          type: boolean
        discoveredBy:
          type: integer

    putSiteMSType:
      properties:
        type:
          type: string

    putSiteTB:
      properties:
        location:
          type: integer
        siteID:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        type:
          type: integer
        verified:
          type: boolean
        visible:
          type: boolean
        discoveredBy:
          type: integer

    putSiteTBType:
      properties:
        type:
          type: string

    putSiteTS:
      properties:
        location:
          type: integer
        siteID:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        status:
          type: integer
        verified:
          type: boolean
        visible:
          type: boolean
        discoveredBy:
          type: integer

    putSiteTSStatus:
      properties:
        type:
          type: string

    putSiteUSS:
      properties:
        location:
          type: integer
        type:
          type: integer
        threatLevel:
          type: integer
        discoveredBy:
          type: integer

    putSiteUSSType:
      properties:
        type:
          type: string
        journalName:
          type: string

## Security
security:
  #- userDiscordAuth: [cmdrWrite, uploadWrite]
  - userAuth: [cmdrWrite, uploadWrite]
  - canonnAuth: [reportDelete, locationDelete, cmdrDelete, uploadDelete, journalDelete, siteDelete, locationWrite, siteWrite]

## Tags
x-tagGroups:
  - name: API Auth
    tags:
      - Local Auth
      - Discord OAuth2
  - name: Reports
    tags:
      - CMDRs
      - Uploads
      - Bark Mound Reports
      - Brain Tree Reports
      - Fungal Gourd Reports
      - Fumarole Reports
      - Generation Ship Reports
      - Guardian Ruin Reports
      - Guardian Structure Reports
      - Geyser Reports
      - Hyperdiction Reports
      - Lava Spout Reports
      - Megaship Reports
      - Thargoid Barnacle Reports
      - Thargoid Structure Reports
      - Tube Worm Reports
      - Unknown Signal Source Reports
  - name: Celestial and Locations
    tags:
      - Systems
      - Bodies
      - Rings
      - Locations
  - name: Sites
    tags:
      - Bark Mounds
      - Brain Trees
      - Fungal Gourds
      - Fumaroles
      - Generation Ships
      - Guardian Ruins
      - Guardian Structures
      - Geysers
      - Hyperdictions
      - Lava Spouts
      - Megaships
      - Thargoid Barnacles
      - Thargoid Structures
      - Tube Worms
      - Unknown Signal Sources
  - name: Testing and Canonn Use
    tags:
      - Journal Data Dumps
tags:

  ## Auth
  - name: Local Auth
    description: Local Authentication for the API
  - name: Discord OAuth2
    description: (Coming Soon) Discord OAuth authentication for the API

  ## Locations
  - name: Systems
    description: Systems stored in our API to use as references for sites
  - name: Bodies
    description: Bodies stored in our API to use as references for sites
  - name: Rings
    description: Rings stored in our API to use as references for sites
  - name: Locations
    description: Combines System, Bodies, and Rings into one endpoint used by sites as a reference

  ## CMDRs
  - name: CMDRs
    description: List of commanders credited with finding sites and their kills

  ## Uploads
  - name: Uploads
    description: Coming soon for storing reporting Screenshots in the API

  ## Journal Data
  - name: Journal Data Dumps
    description: Testing platform for raw journal dumps, Canonn Only Use

  ## Bark Mounds
  - name: Bark Mounds
    description: Code Name - BM
  - name: Bark Mound Reports
    description: Public Reporting of BM

  ## Brain Trees
  - name: Brain Trees
    description: Code Name - BT
  - name: Brain Tree Reports
    description: Public Reporting of BT

  ## Fungal Gourds
  - name: Fungal Gourds
    description: Code Name - FG
  - name: Fungal Gourd Reports
    description: Public Reporting of FG

  ## Fumaroles
  - name: Fumaroles
    description: Code Name - FM
  - name: Fumarole Reports
    description: Public Reporting of FM

  ## Generation Ships
  - name: Generation Ships
    description: Code Name - GEN
  - name: Generation Ship Reports
    description: Public Reporting of GEN

  ## Guardian Ruins
  - name: Guardian Ruins
    description: Code Name - GR
  - name: Guardian Ruin Reports
    description: Public Reporting of GR

  ## Guardian Structures
  - name: Guardian Structures
    description: Code Name - GS
  - name: Guardian Structure Reports
    description: Public Reporting of GS

  ## Geysers
  - name: Geysers
    description: Code Name - GY
  - name: Geyser Reports
    description: Public Reporting of GY

  ## Hyperdictions
  - name: Hyperdictions
    description: Code Name - HD
  - name: Hyperdiction Reports
    description: Public Reporting of HD

  ## Lava Spouts
  - name: Lava Spouts
    description: Code Name - LS
  - name: Lava Spout Reports
    description: Public Reporting of LS

  ## Megaships
  - name: Megaships
    description: Code Name - MS
  - name: Megaship Reports
    description: Public Reporting of MS

  ## Thargoid Barnacles
  - name: Thargoid Barnacles
    description: Code Name - TB
  - name: Thargoid Barnacle Reports
    description: Public Reporting of TB

  ## Thargoid Structures
  - name: Thargoid Structures
    description: Code Name - TS
  - name: Thargoid Structure Reports
    description: Public Reporting of TS

  ## Tube Worms
  - name: Tube Worms
    description: Code Name - TW
  - name: Tube Worm Reports
    description: Public Reporting of TW

  ## Unknown Signal Sources
  - name: Unknown Signal Sources
    description: Code Name - USS
  - name: Unknown Signal Source Reports
    description: Public Reporting of USS
