module.exports = {
  settings: {
    sentry: {
      enabled: true,
    },
    cache: {
      enabled: false,
      type: 'redis',
      maxAge: 3600000,
      models: [
        { model: 'bodies', maxAge: 60000 },
        { model: 'systems', maxAge: 60000 },
        { model: 'rings', maxAge: 60000 },
        { model: 'excludeclients', maxAge: 30000 },
        { model: 'excludecmdrs', maxAge: 30000 },
        { model: 'excludecodices', maxAge: 30000 },
        { model: 'excludeevents', maxAge: 30000 },
        { model: 'excludefsses', maxAge: 30000 },
        { model: 'permitlocks', maxAge: 3600000 },
        { model: 'apsites', maxAge: 60000 },
        { model: 'bmsites', maxAge: 60000 },
        { model: 'btsites', maxAge: 60000 },
        { model: 'cssites', maxAge: 60000 },
        { model: 'fgsites', maxAge: 60000 },
        { model: 'fmsites', maxAge: 60000 },
        { model: 'gbsites', maxAge: 60000 },
        { model: 'gensites', maxAge: 60000 },
        { model: 'grsites', maxAge: 60000 },
        { model: 'gssites', maxAge: 60000 },
        { model: 'gvsites', maxAge: 60000 },
        { model: 'gysites', maxAge: 60000 },
        { model: 'lssites', maxAge: 60000 },
        { model: 'tbsites', maxAge: 60000 },
        { model: 'tssites', maxAge: 60000 },
        { model: 'twsites', maxAge: 60000 },
        { model: 'aptypes', maxAge: 3600000 },
        { model: 'bmtypes', maxAge: 3600000 },
        { model: 'bttypes', maxAge: 3600000 },
        { model: 'cstypes', maxAge: 3600000 },
        { model: 'fgtypes', maxAge: 3600000 },
        { model: 'fmtypes', maxAge: 3600000 },
        { model: 'grtypes', maxAge: 3600000 },
        { model: 'gstypes', maxAge: 3600000 },
        { model: 'gvtypes', maxAge: 3600000 },
        { model: 'gytypes', maxAge: 3600000 },
        { model: 'lstypes', maxAge: 3600000 },
        { model: 'tbtypes', maxAge: 3600000 },
        { model: 'tbsubtypes', maxAge: 3600000 },
        { model: 'tbcycles', maxAge: 3600000 },
        { model: 'tsstatuses', maxAge: 3600000 },
        { model: 'twtypes', maxAge: 3600000 }
      ]
    },
    parser: {
      enabled: true,
      multipart: true,
      formLimit: '128mb',
      jsonLimit: '256mb',
    },
    gzip: {
      enabled: true,
    },
    responseTime: {
      enabled: true,
    },
    poweredBy: {
      enabled: true,
      value: 'Canonn APIv2 <docs.canonn.tech>',
    },
    cors: {
      enabled: true,
      origin: '*',
      expose: ['WWW-Authenticate', 'Server-Authorization', 'Content-Range'],
      credentials: true,
      methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'HEAD'],
      headers: [
        'Content-Type',
        'Authorization',
        'X-Frame-Options',
        'Origin',
        'Accept',
      ],
    },
  },
};
